#!/usr/bin/env python
# -*- coding: utf-8 -*-

import random

VERSION = "1.0.0"
VERSION_NAME = "Dependent Griffin"

adj=[]

adj.append("Aggressive")
adj.append("Arrogant")
adj.append("Belligerent")
adj.append("Big-headed")
adj.append("Bitchy")
adj.append("Boastful")
adj.append("Bone-idle")
adj.append("Boorish")
adj.append("Boring")
adj.append("Bossy")
adj.append("Cantankerous")
adj.append("Careless")
adj.append("Clinging")
adj.append("Compulsive")
adj.append("Conservative")
adj.append("Coward")
adj.append("Cruel")
adj.append("Cynical")
adj.append("Dazzling")
adj.append("Deadly")
adj.append("Dead to")
adj.append("Deaf")
adj.append("Deaf-and-dumb")
adj.append("deceitful")
adj.append("Decorative")
adj.append("Decorous")
adj.append("Decrepit")
adj.append("Deducible")
adj.append("Deductive")
adj.append("Deep")
adj.append("Deep-drawn")
adj.append("Deep-rooted")
adj.append("Deep-seated")
adj.append("Defamatory")
adj.append("Defective")
adj.append("Defenseless")
adj.append("Defensible")
adj.append("Defensive")
adj.append("Deferential")
adj.append("Deferred")
adj.append("Defiant")
adj.append("Deficient")
adj.append("Definable")
adj.append("Definite")
adj.append("Definitive")
adj.append("Deformed")
adj.append("Deft")
adj.append("Defunct")
adj.append("Degenerate")
adj.append("Degraded")
adj.append("Degrading")
adj.append("Dehiscent")
adj.append("Dejected")
adj.append("Delectable")
adj.append("Deliberate")
adj.append("Delicious")
adj.append("Deliquescent")
adj.append("Delirious")
adj.append("Delphic")
adj.append("Delusive")
adj.append("Demagogic")
adj.append("Demagogical")
adj.append("Demented")
adj.append("Democratic")
adj.append("Demonic")
adj.append("Demonstrable")
adj.append("Demonstrative")
adj.append("Demountable")
adj.append("Demure")
adj.append("Deniable")
adj.append("Dense")
adj.append("Dentilabial")
adj.append("Departed")
adj.append("Departmental")
adj.append("Dependent")
adj.append("Depilatory")
adj.append("Deplorable")
adj.append("Depraved")
adj.append("Deprecatory")
adj.append("Depreciatory")
adj.append("Depressed")
adj.append("Depressive")
adj.append("Deprived of")
adj.append("Deranged")
adj.append("Derelict")
adj.append("Derisive")
adj.append("Derisory")
adj.append("Derived")
adj.append("Derogatory")
adj.append("Describable")
adj.append("Descriptive")
adj.append("Desert")
adj.append("Designed")
adj.append("Desirous")
adj.append("Desperate")
adj.append("Despicable")
adj.append("Despondent")
adj.append("Despotic")
adj.append("Destitute")
adj.append("Destructible")
adj.append("Desultory")
adj.append("Detachable")
adj.append("detached")
adj.append("Detached")
adj.append("Detectable")
adj.append("Determinant")
adj.append("Deterrent")
adj.append("Detestable")
adj.append("Detrimental")
adj.append("Developmental")
adj.append("Deviationist")
adj.append("Devilish")
adj.append("Devious")
adj.append("Dexterous")
adj.append("Diabolic")
adj.append("Diagonal")
adj.append("Diagrammatic")
adj.append("Dialectic")
adj.append("Dialectical")
adj.append("Diametrical")
adj.append("Dictatorial")
adj.append("Dielectric")
adj.append("Differential")
adj.append("Difficult")
adj.append("Diffuse")
adj.append("Digestible")
adj.append("Digestive")
adj.append("Digital")
adj.append("Dihedral")
adj.append("Dilapidated")
adj.append("Dingy")
adj.append("Dionysian")
adj.append("Diphthongal")
adj.append("Diplomatic")
adj.append("Dire")
adj.append("Directive")
adj.append("Direful")
adj.append("Dirt-cheap")
adj.append("Dirty")
adj.append("Disabled")
adj.append("Disadvantageous")
adj.append("Disagreeable")
adj.append("Disappointed")
adj.append("Disastrous")
adj.append("Disconnected")
adj.append("Disconsolate")
adj.append("Discontent")
adj.append("Discontinuous")
adj.append("Discouraging")
adj.append("Discourteous")
adj.append("Discreditable")
adj.append("Discriminating")
adj.append("Discursive")
adj.append("Disdainful")
adj.append("Diseased")
adj.append("Disembodied")
adj.append("Disengaged")
adj.append("Disgraceful")
adj.append("Disgusted")
adj.append("Disgustful")
adj.append("Disgusting")
adj.append("Disheveled")
adj.append("dishonest")
adj.append("Dishonest")
adj.append("Dishonorable")
adj.append("Disinfected")
adj.append("Disingenuous")
adj.append("Disinterested")
adj.append("Disjointed")
adj.append("Disjunctive")
adj.append("Disloyal")
adj.append("Dismal")
adj.append("Disobedient")
adj.append("Dispassionate")
adj.append("Dispensable")
adj.append("Displeased")
adj.append("Disposable")
adj.append("Disputable")
adj.append("Disquieting")
adj.append("Disreputable")
adj.append("Disrespectful")
adj.append("Disruptive")
adj.append("Dissatisfied")
adj.append("Dogmatic")
adj.append("Domineering")
adj.append("Finicky")
adj.append("Flirtatious")
adj.append("Foolish")
adj.append("Fussy")
adj.append("Greedy")
adj.append("Grumpy")
adj.append("Gullible")
adj.append("Harsh ")
adj.append("Impatient")
adj.append("Impolite")
adj.append("Impulsive")
adj.append("Inconsiderate")
adj.append("Inconsistent")
adj.append("Indecisive")
adj.append("Indiscreet")
adj.append("Inflexible")
adj.append("Interfering")
adj.append("Intolerant")
adj.append("Irresponsible")
adj.append("Jealous")
adj.append("Lazy")
adj.append("Machiavellian")
adj.append("Materialistic")
adj.append("Mean")
adj.append("Miserly")
adj.append("Moody")
adj.append("Narrow-minded")
adj.append("Nasty")
adj.append("Naughty")
adj.append("Nervous")
adj.append("Obsessive")
adj.append("Obstinate")
adj.append("Overcritical")
adj.append("Overemotional")
adj.append("Patronizing")
adj.append("Perverse")
adj.append("Pessimistic")
adj.append("Pompous")
adj.append("Possessive")
adj.append("Procrastinator")
adj.append("Pusillanimous")
adj.append("Quarrelsome")
adj.append("Quick-tempered")
adj.append("Resentful")
adj.append("Rude")
adj.append("Ruthless")
adj.append("Sarcastic")
adj.append("Secretive")
adj.append("Self-centred")
adj.append("Self-indulgent")
adj.append("Selfish")
adj.append("Shiftless")
adj.append("Silly")
adj.append("Sneaky")
adj.append("Stingy")
adj.append("Stubborn")
adj.append("Stupid")
adj.append("Sullen")
adj.append("Superficial")
adj.append("Tactless")
adj.append("Thoughtless")
adj.append("Timid")
adj.append("Touchy")
adj.append("Truculent")
adj.append("Unkind")
adj.append("Unpredictable")
adj.append("Unreliable")
adj.append("Untidy")
adj.append("Untrustworthy")
adj.append("Vague")
adj.append("Vain")
adj.append("Vengeful")
adj.append("Vulgar")
adj.append("Weak-willed")


db=[]

db.append(["Aatxe","Basque","A spirit that takes the form of a bull."])
db.append(["Abaasy","Yakuts","Demons that have teeth of iron"])
db.append(["Abada","African","Small type of unicorn reported to live in the lands of the African Congo."])
db.append(["Äbädä","Tatar","Forest spirit."])
db.append(["Abaia","Melanesia","Huge magical eel."])
db.append(["Á Bao A Qu","Malay","An entity that lives in the Tower of Victory in Chitor."])
db.append(["Abarimon","Medieval Bestiaries","Savage humanoid with backward feet."])
db.append(["Abath","Malay","One-horned animal."])
db.append(["Abura-sumashi","Japanese","Creature from a mountain pass in Kumamoto Prefecture."])
db.append(["Acephali","Greek","Headless humanoids."])
db.append(["Acheri","Indian","Disease-bringing ghost."])
db.append(["Achlis","Roman","Curious elk."])
db.append(["Adar Llwch Gwin","Welsh","Giant birds that understand human languages."])
db.append(["Adaro","Solomon Islands","Malevolent merfolk."])
db.append(["Adhene","Manx","Nature spirit."])
db.append(["Adlet","Inuit","Vampiric dog-human hybrid."])
db.append(["Adroanzi","Lugbara","Nature spirit."])
db.append(["Adze","Ewe people","An African vampiric-forest being."])
db.append(["Aerico","Greek","Disease demon."])
db.append(["Afanc","Welsh","Lake monster (exact lake varies by story)."])
db.append(["Agathodaemon","Greek","Spirit of vinefields and grainfields."])
db.append(["Agloolik","Inuit","Ice spirit that aids hunters and fishermen."])
db.append(["Agni","Hindu","God of fire and sacrifices."])
db.append(["Agogwe","East Africa","Small, ape-like humanoid."])
db.append(["Ahkiyyini","Inuit","Animated skeleton that causes shipwrecks."])
db.append(["Ahuizotl","Aztec","Anthropophagous dog-monkey hybrid."])
db.append(["Aigamuxa","Khoikhoi","Anthropophagous humanoid with eyes in its instep."])
db.append(["Aigikampoi","Etruscan","Fish-tailed goat."])
db.append(["Airavata","Hindu","Divine Elephant."])
db.append(["Aitu","Polynesian","Malevolent spirits or demons."])
db.append(["Aitvaras","Lithuanian","Household spirit."])
db.append(["Ajatar","Finnish","Dragon."])
db.append(["Akateko","Japanese","Tree-dwelling monster."])
db.append(["Akhlut","Inuit","Orca-wolf shapeshifter."])
db.append(["Akka","Finnish","Female spirits or minor goddesses."])
db.append(["Akki","Japanese","Large, grotesque humanoid."])
db.append(["Akkorokamui","Ainu","Sea monster."])
db.append(["Akuma","Japanese","Evil spirit."])
db.append(["Akupara","Hindu","Giant turtle that supports the world."])
db.append(["Akurojin-no-hi","Japanese","Ghostly flame which causes disease."])
db.append(["Alal","Chaldean","queen of the full moon."])
db.append(["Alan","Philippine","Winged humanoid that steals reproductive waste to make children."])
db.append(["Al","Armenian and Persian","Spirit that steals unborn babies and livers from pregnant women."])
db.append(["Ala","Slavic","Bad weather demon."])
db.append(["Alce","Heraldic","Wingless griffin."])
db.append(["Aleya","Bengali","Spirit of a dead fisherman."])
db.append(["Alicanto","Chilean","Bird that eats gold and silver."])
db.append(["Alicorn","A winged unicorn from the Latin 'ala'","wing) and 'corn'","horn)."])
db.append(["Alkonost","Slavic","Angelic bird with human head and breasts."])
db.append(["Allocamelus","Heraldic","Ass-camel hybrid."])
db.append(["Almas","Mongolian","Savage humanoid."])
db.append(["Al-mi'raj","Islamic","One-horned rabbit."])
db.append(["Aloja","Catalan","Female water spirit."])
db.append(["Alom-bag-winno-sis","Abenaki","Little people and tricksters."])
db.append(["Alp","German","Male night-demon."])
db.append(["Alphyn","Heraldic","Lion-like creature, sometimes with dragon or goat forelegs."])
db.append(["Alp-luachra","Irish","Parasitic fairy."])
db.append(["Al Rakim","Islamic","Guard dog of the Seven Sleepers."])
db.append(["Alseid","Greek","Grove nymph."])
db.append(["Alû","Assyrian","Leprous demon."])
db.append(["Alux","Mayan","Little people."])
db.append(["Amaburakosagi","Japanese","Ritual disciplinary demon from Shikoku."])
db.append(["Amala","Tsimshian","Giant who holds up the world."])
db.append(["Amamehagi","Japanese","Ritual disciplinary demon from Hokuriku."])
db.append(["Amanojaku","Japanese","Small demon."])
db.append(["Amarok","Inuit","Giant wolf."])
db.append(["Amarum","Quechua","Water boa spirit."])
db.append(["Amazake-babaa","Japanese","Disease-causing hag."])
db.append(["Amemasu","Ainu","Lake monster."])
db.append(["Ammit","Ancient Egyptian","Female demon with a body that was part lion, hippopotamus and crocodile."])
db.append(["Amorōnagu","Japanese","Tennyo from the island of Amami Ōshima."])
db.append(["Amphiptere","Heraldic","Winged serpent."])
db.append(["Amphisbaena","Greek","Serpent with a head at each end."])
db.append(["Anakim","Jewish","Giant."])
db.append(["Androsphinx","Ancient Egyptian","Human-headed sphinx."])
db.append(["Angel","mainly Christian, Jewish, Islamic traditions","From the Greek ángelos, divine beings of Heaven who act as mediators between God and humans; the counterparts of Demons."])
db.append(["Angha","Persian","Dog-lion-peacock hybrid."])
db.append(["Ani Hyuntikwalaski","Cherokee","Lightning spirit."])
db.append(["Ankou","French","Skeletal grave watcher with a lantern and a scythe."])
db.append(["Anmo","Japanese","Ritual disciplinary demon from Iwate Prefecture."])
db.append(["Antaeus","Greek","A giant who was extremely strong as long as he remained in contact with the ground."])
db.append(["Antero Vipunen","Finnish","Subterranean giant."])
db.append(["Ao Ao","Guaraní","Anthropophagous peccary or sheep."])
db.append(["Aobōzu","Japanese","Blue monk who kidnaps children."])
db.append(["Apkallu","Sumerian","Fish-human hybrid that attends the god Enki."])
db.append(["Apsaras","Buddhist and Hindu","Female cloud spirit."])
db.append(["Aqrabuamelu","Akkadian","Human-scorpion hybrid."])
db.append(["Ardat-Lili","Akkadian","Disease demon."])
db.append(["Argus Panoptes","Greek","Hundred-eyed giant."])
db.append(["Arikura-no-baba","Japanese","Old woman with magical powers."])
db.append(["Arimaspi","Greek","One-eyed humanoid."])
db.append(["Arion","Greek","Extremely swift horse with a green mane and the power of speech."])
db.append(["Arkan Sonney","Manx","Fairy hedgehog."])
db.append(["Asag","Sumerian","Hideous rock demon."])
db.append(["Asakku","Sumerian","Demon."])
db.append(["Asanbosam","West Africa","Iron-toothed vampire."])
db.append(["Asena","Turkic","Blue-maned wolf."])
db.append(["A-senee-ki-wakw","Abenaki","Stone-giant."])
db.append(["Ashi-magari","Japanese","Invisible tendril that impedes movement."])
db.append(["Asiman","Dahomey","Vampiric possession spirit."])
db.append(["Askefrue","Germanic","Female tree spirit."])
db.append(["Ask-wee-da-eed","Abenaki","Fire elemental and spectral fire."])
db.append(["Asobibi","Japanese","Spectral fire from Kōchi Prefecture."])
db.append(["Aspidochelone","Medieval Bestiaries","Island-sized whale or sea turtle."])
db.append(["Asrai","English","Water spirit."])
db.append(["Astomi","Greek","Humanoid sustained by pleasant smells instead of food."])
db.append(["Aswang","Philippine","Carrion-eating humanoid."])
db.append(["Atomy","English","Surprisingly small creature."])
db.append(["Ato-oi-kozō","Japanese","Invisible spirit that follows people."])
db.append(["Atshen","Inuit","Anthropophagous spirit."])
db.append(["Auloniad","Greek","Pasture nymph."])
db.append(["Avalerion","Medieval Bestiary","King of the birds."])
db.append(["Awa-hon-do","Abenaki","Insect spirit."])
db.append(["Axex","Ancient Egyptian","Falcon-lion hybrid."])
db.append(["Ayakashi","Japanese","Sea-serpent that travels over boats in an arc while dripping oil."])
db.append(["Ayakashi-no-ayashibi","Japanese","Spectral fire from Ishikawa Prefecture."])
db.append(["Aziza","Dahomey","Little people that help hunters."])
db.append(["Azukiarai","Japanese","Spirit that washes azuki beans along riversides."])
db.append(["Azukibabaa","Japanese","Bean-grinding hag who devours people."])
db.append(["Azukitogi","Japanese","Spirit that washes azuki beans along riversides."])
db.append(["Baba Yaga","Slavic","Forest spirit and hag"])
db.append(["Backoo","Guyanese","Malevolent little people"])
db.append(["Ba","Egyptian","Soul of the deceased, depicted as a bird or a human-headed bird."])
db.append(["Bagiennik","Slavic","Malevolent water spirit"])
db.append(["Bahamut","Arabian","Giant fish"])
db.append(["Bai Ze","Chinese","Talking beast which handed down knowledge on harmful spirits"])
db.append(["Ba Jiao Gui","Chinese","Banana tree spirit"])
db.append(["Bake-kujira","Japanese","Ghostly whale skeleton that drifts along the coastline of Shimane Prefecture"])
db.append(["Bakeneko","Japanese","Magical cat"])
db.append(["Bakezōri","Japanese","Animated straw sandal"])
db.append(["Bakhtak","Iranian","Night demon"])
db.append(["Baku","Japanese","Dream-devouring, tapir-like creature"])
db.append(["Bakunawa","Philippine","Sea serpent that causes eclipses"])
db.append(["Balaur","Romanian","Multi-headed dragon"])
db.append(["Bannik","Slavic","Bathhouse spirit"])
db.append(["Banshee","Irish","Death spirit"])
db.append(["Baobhan Sith","Celtic Mythology","Beautiful vampiric seductresses who prey on young travelers by night"])
db.append(["Barbegazi","Swiss","Dwarf with giant, snowshoe-like feet"])
db.append(["Bardi","Trabzon","Shapechanging death spirit"])
db.append(["Barghest","Yorkshire black dog"])
db.append(["Bar Juchne","Abrahamic and Talmudic","Bird."])
db.append(["Bar Juchne","Jewish","Gigantic bird."])
db.append(["Barnacle Geese","Medieval folklore","Geese which hatch from barnacles."])
db.append(["Barong","Balinese","Tutelary spirit."])
db.append(["Basajaun","Basque","Ancestral, megalith-building race."])
db.append(["BasCelik","Serbian","Powerful, evil winged man whose soul is not held by his body and can be subdued only by causing him to suffer dehydration."])
db.append(["Bashe","Chinese","Elephant-swallowing serpent."])
db.append(["Basilisco Chilote","Chilota","Chicken-serpent hybrid."])
db.append(["Basilisk","Italian","Multi-limbed, venomous lizard."])
db.append(["Batibat","Philippine","Female night-demon."])
db.append(["Batsu","Chinese","Drought spirit."])
db.append(["Baubas","Lithuanian","Malevolent spirit."])
db.append(["Baykok","Ojibwa","Flying skeleton."])
db.append(["Bean Nighe","Irish","Death spirit; a type of Banshee/Bean Sídhe."])
db.append(["Behemoth","Jewish","Massive beast, possibly like a dinosaur or crocodile"])
db.append(["Bendigeidfran","Welsh","Giant king"])
db.append(["Bennu","Egyptian","Heron-like, regenerative bird, equivalent to (or inspiration for) the Phoenix"])
db.append(["Berehynia","Slavic","Water spirit."])
db.append(["Bergrisar","Norse","Mountain giants who live alongside the Hrimthursar(lit. 'Rime-Giants') in Jotunheim"])
db.append(["Bergsrå","Norse","Mountain spirit"])
db.append(["Bestial beast","Brazilian","Centauroid specter"])
db.append(["Betobeto-san","Japanese","Invisible spirit which follows people at night, making the sound of footsteps"])
db.append(["Bhūta","Buddhist and Hindu","Ghost of someone killed by execution or suicide"])
db.append(["Bi-blouk","Khoikhoi","Female, anthropophagous, partially invisible monster"])
db.append(["Bies","Slavic","Demon"])
db.append(["Bigfoot","American folklore","Forest-dwelling apeman."])
db.append(["Binbōgami","Japanese","Spirit of poverty"])
db.append(["Bishop-fish","Medieval Bestiaries","Fish-like humanoid"])
db.append(["Biwa-bokuboku","Japanese","Animated biwa"])
db.append(["Black Annis","English","Blue-faced hag"])
db.append(["Black Dog","British","Canine death spirit"])
db.append(["Black Shuck","Norfolk, Essex, and Suffolk","black dog"])
db.append(["Blemmyae","Medieval Bestiary","Headless humanoid with face in torso"])
db.append(["Bloody Bones","Irish","Water bogeyman"])
db.append(["Bluecap","English","Mine-dwelling fairy"])
db.append(["Blue Crow","Brazilian","a giant amazonian bird."])
db.append(["Bodach","Scottish","Malevolent spirit"])
db.append(["Bogeyman","English","Malevolent spirit"])
db.append(["Boggart","English","Malevolent household spirit"])
db.append(["Boginki","Polish","Nature spirit"])
db.append(["Bogle","Scottish","Malevolent spirit"])
db.append(["Boi-tatá","Brazilian","Giant snake"])
db.append(["Bokkenrijders","Dutch","ghosts/devils riding flying goats; co-opted by bandits to instil fear during raids"])
db.append(["Bolla","Albanian","Dragon"])
db.append(["Bonnacon","Medieval Bestiaries","Bull-horse hybrid with flaming dung"])
db.append(["Boobrie","Scottish","Roaring water bird"])
db.append(["Boo Hag","American Folklore","Vampire-like creature that steals energy from sleeping victims"])
db.append(["Bozaloshtsh","Slavic","Death spirit"])
db.append(["Brag","English","Malevolent water horse"])
db.append(["Brownie","English and Scottish","Benevolent household spirit"])
db.append(["Broxa","Jewish","Nocturnal bird that drains goats of their milk"])
db.append(["Bugbear","English","Bearlike goblin"])
db.append(["Buggane","Manx","Ogre-like humanoid"])
db.append(["Bugul Noz","Celtic","Extremely ugly, but kind, forest spirit"])
db.append(["Bukavac","Serbia","Six-legged lake monster"])
db.append(["Bunyip","Australian Aboriginal","Horse-walrus hybrid lake monster"])
db.append(["Buraq","Islamic","Human-headed, angelic horse"])
db.append(["Bush Dai Dai","Guyanese","Spirit that seduces and kills men"])
db.append(["Byangoma","Bengali","Fortune-telling birds"])
db.append(["Bysen","Scandinavian","Diminutive forest spirit"])
db.append(["Cabeiri","Greek","Smith and wine spirit"])
db.append(["Cacus","Roman","Fire-breathing giant"])
db.append(["Cadejo","Central America","Cow-sized dog-goat hybrid in two varieties: benevolent and white; malevolent and black"])
db.append(["Caipora","Tupi","Fox-human hybrid and nature spirit"])
db.append(["Caladrius","Medieval Bestiary","White bird that can foretell if a sick person will recover or die"])
db.append(["Calingi","Medieval Bestiary","Humanoid with an eight-year lifespan"])
db.append(["Callitrix","Medieval Bestiary","Apes who always bear twins, one the mother loves, the other it hates"])
db.append(["Calydonian Boar","Greek","Giant, chthonic boar"])
db.append(["Calygreyhound","Heraldic","Wildcat-deer/antelope-eagle-ox-lion hybrid"])
db.append(["Camahueto","Chilota","One-horned calf"])
db.append(["Cambion","Medieval folklore","Offspring of a human and an incubus or succubus; general term for any kind of human/demon hybrid"])
db.append(["Campe","Greek","Dragon-human-scorpion hybrid"])
db.append(["Camulatz","Mayan","Bird that ate the heads of the first men"])
db.append(["Canaima","Guyanese","Were-jaguar"])
db.append(["Candileja","Colombian","Spectral, fiery hag"])
db.append(["Canotila","Lakota","Little people and tree spirits"])
db.append(["Caoineag","Scottish","Death spirit (a particular type of Banshee/Bean Sídhe)"])
db.append(["Căpcăun","Romanian","Large, monstrous humanoid"])
db.append(["Carbuncle","Latin America","Small creature with a jewel on its head"])
db.append(["Catoblepas","Medieval Bestiary","Scaled buffalo-hog hybrid"])
db.append(["Cat Sidhe","Scottish","Fairy cat"])
db.append(["Ceffyl Dŵr","Welsh","Malevolent water horse"])
db.append(["Centaur","Greek","Human-horse hybrid"])
db.append(["Centicore Indian mythology Indian- Horse-Antelope-Lion-Bear hybrid"])
db.append(["Cerastes","Greek","Extremely flexible, horned snake"])
db.append(["Cerberus","Greek","Three-headed dog that guards the entrance to the underworld"])
db.append(["Cercopes","Greek","Mischievous forest spirit"])
db.append(["Cericopithicus","Medieval Bestiary","Apes who always bear twins, one the mother loves, the other it hates"])
db.append(["Ceryneian Hind","Greek","Hind with golden antlers and bronze or brass hooves"])
db.append(["Cetan","Lakota","Hawk spirit"])
db.append(["Chakora","Hindu","Lunar bird"])
db.append(["Chamrosh","Persian","Dog-bird hybrid"])
db.append(["Chaneque","Aztec","Little people and nature spirits"])
db.append(["Changeling","European","Humanoid child","fairy, elf, troll, etc.) substituted for a kidnapped human child"])
db.append(["Čhápa","Lakota","Beaver spirit"])
db.append(["Charybdis","Greek","Sea monster in the form of a giant mouth"])
db.append(["Chepi","Narragansett","Ancestral spirit that instructs tribe members"])
db.append(["Cherufe","Mapuche","Volcano-dwelling monster"])
db.append(["Chibaiskweda","Abenaki","Ghost of an improperly buried person"])
db.append(["Chichevache","Medieval folklore","Human-faced cow that feeds on good women"])
db.append(["Chickcharney","Bahamian","Bird-mammal hybrid"])
db.append(["Chimaera","Greek","Lion-goat-snake hybrid"])
db.append(["Chimbwe","(hyena) in Tumbuka","an ethnic group living in Malawi, Zambia and Tanzania) mythology"])
db.append(["Chindi","Navajo","Vengeful ghost that causes dust devils"])
db.append(["Chinthe","Burmese","Temple-guarding feline, similar to Chinese Shi and Japanese Shisa"])
db.append(["Chitauli","Zulu","Human-lizard hybrid"])
db.append(["Chōchinobake","Japanese","Animated paper lantern"])
db.append(["Chollima","Korean","Supernaturally fast horse"])
db.append(["Chonchon","Mapuche","Disembodied, flying head"])
db.append(["Choorile","Guyanese","Ghost of a woman that died in childbirth"])
db.append(["Chromandi","Medieval Bestiary","Hairy savage with dog teeth"])
db.append(["Chrysaor","Greek","Son of the gorgon Medusa, imaged as a giant or a winged boar"])
db.append(["Chrysomallus","Greek mythology","Golden haired winged ram"])
db.append(["Chukwa","Hindu","Giant turtle that supports the world"])
db.append(["Chupacabra","Latin America","Cryptid beast, named for its habit of sucking the blood of goats and other livestock"])
db.append(["Churel","Hindu","Vampiric, female ghost"])
db.append(["Ciguapa","Dominican Republic","Malevolent seductress"])
db.append(["Cihuateteo","Aztec","Ghost of women that died in childbirth"])
db.append(["Cikavac","Serbian","Bird that serves its owner"])
db.append(["Cinnamon bird","Medieval Bestiaries","Giant bird that makes its nest out of cinnamon"])
db.append(["Cipactli","Aztec","Sea monster, crocodile-fish hybrid"])
db.append(["Cirein cròin","Scottish","Sea serpent"])
db.append(["Cluricaun","Irish","Leprechaun-like Little people that are permanently drunk"])
db.append(["Coblynau","Welsh","Little people and mine spirits"])
db.append(["Cockatrice","Medieval Bestiaries","Chicken-lizard hybrid"])
db.append(["Cofgod","English","Cove god"])
db.append(["Colo Colo","Mapuche","Rat-bird hybrid that can shapeshift into a serpent"])
db.append(["Corycian nymphs","Greek","Nymph of the Corycian Cave"])
db.append(["Cretan Bull","Greek","Monstrous bull"])
db.append(["Crinaeae","Greek","Fountain nymph"])
db.append(["Criosphinx","Ancient Egypt","Ram-headed sphinx"])
db.append(["Crocotta","Medieval Bestiaries","Monstrous dog-wolf"])
db.append(["Cuco","Latin America","Bogeyman"])
db.append(["Cucuy","Latin America","Malevolent spirit"])
db.append(["Cuegle","Cantabrian","Monstrous, three-armed humanoid"])
db.append(["Cuélebre","Asturian and Cantabrian","Dragon"])
db.append(["Curupira","Tupi","Nature spirit"])
db.append(["Cu Sith","Scottish","Gigantic fairy dog"])
db.append(["Cŵn Annwn","Welsh","Underworld hunting dog"])
db.append(["Cyclops","Greek","One-eyed giant"])
db.append(["Cyhyraeth","Welsh","Death spirit"])
db.append(["Cynocephalus","Medieval Bestiaries","Dog-headed humanoid"])
db.append(["Dactyl","Greek","Little people and smith and healing spirits"])
db.append(["Daemon","Greek","Incorporeal spirit"])
db.append(["Dahu","France, Switzerland and the north of Italy","like a deer or ibex with legs on one side of its body are shorter than on the other side"])
db.append(["Daidarabotchi","Japanese","Giant responsible for creating many geographical features in Japan"])
db.append(["Daitengu","Japanese","The most powerful class of tengu, each of whom lives on a separate mountain"])
db.append(["Daitya","Hindu","Giant"])
db.append(["Danava","Hindu","Water demon"])
db.append(["Daphnaie","Greek","Laurel tree nymph"])
db.append(["Datsue-ba","Japanese","Old woman who steals clothes from the souls of the dead"])
db.append(["Dead Sea Apes","Islamic","Human tribe turned into apes for ignoring Moses' message"])
db.append(["Deer Woman","Native American","Human-deer hybrid"])
db.append(["Deity","Global","Preternatural or supernatural possibly immortal being"])
db.append(["Demigod","Global","Half human, half god."])
db.append(["Demon","Global","From the Greek daímon, chthonic entities of Hell often seen as Satan's minions who are inimical to mankind; the counterparts of Angels."])
db.append(["Dhampir","Balkans","Human/vampire hybrid"])
db.append(["Diao Si Gui","Chinese","Hanged ghost"])
db.append(["Dilong","Chinese","Earth dragon"])
db.append(["Dip","Catalan","Demonic and vampiric dog"])
db.append(["Di Penates","Roman","House spirit"])
db.append(["Dipsa","Medieval Bestiaries","Extremely poisonous snake"])
db.append(["Dirawong","Australian Aboriginal","Goanna spirit"])
db.append(["Di sma undar jordi","Gotland","Little people and nature spirits"])
db.append(["Diwata","Philippine","Tree spirit"])
db.append(["Djinn","Islam","Genii"])
db.append(["Dobhar-chu","Irish","Dog-fish hybrid"])
db.append(["Do-gakw-ho-wad","Abenaki","Little people"])
db.append(["Dokkaebi","Korean","Grotesque, horned humanoids"])
db.append(["Dökkálfar","Norse","Male ancestral spirits; the Dark Elves"])
db.append(["Dola","Slavic","Tutelary and fate spirit"])
db.append(["Domovoi","Slavic","House spirit"])
db.append(["Doppelgänger","German","Ghostly double"])
db.append(["Drac","Catalan","Lion or bull-faced dragon"])
db.append(["Drac","French","Winged sea serpent"])
db.append(["Dragon","Many cultures worldwide","Fire-breathing and winged (normally)"])
db.append(["Dragon turtle","Chinese","Giant turtle with dragon-like head"])
db.append(["Drakaina","Greek","Dragons depicted with female characteristics"])
db.append(["Drakon","Greek","A snakelike creature with bat wings acidic breath and a paralyzing stare."])
db.append(["Draugr","Norse","Undead"])
db.append(["Drekavac","Slavic","Restless ghost of an unbaptised child"])
db.append(["Drop Bear","Australian","Large carnivorous koala that hunts by dropping on its prey from trees"])
db.append(["Drow","Scottish","Cavern spirit"])
db.append(["Drude","German","Possessing demon"])
db.append(["Druk","Bhutanese","Dragon"])
db.append(["Dryad","Greek","Tree nymph"])
db.append(["Duende","Spanish and Portuguese","Little people and forest spirits"])
db.append(["Duergar","English","Malevolent little people"])
db.append(["Dullahan","Irish","Headless death spirit"])
db.append(["Duwende","Philippine","Little people, some are house spirits, others nature spirits"])
db.append(["Dvergr","Norse","Subterranean little people smiths"])
db.append(["Dvorovoi","Slavic","Courtyard spirit"])
db.append(["Dwarf","Germanic","Little people nature spirits"])
db.append(["Dybbuk","Jewish","A spirit (sometimes the soul of a wicked deceased) that possesses the living"])
db.append(["Dzee-dzee-bon-da","Abenaki","Hideous monster"])
db.append(["Dzunukwa","Kwakwaka'wakw","Child-eating hag"])
db.append(["Each Uisge","Scottish","Malevolent water horse"])
db.append(["Eachy","English and Scottish","Humanoid lake monster"])
db.append(["Eagle Spirit","Many cultures worldwide","Leadership or guidance totem"])
db.append(["Ebu Gogo","Flores","Diminutive humanoids, possibly inspired by Homo floresiensis"])
db.append(["Echeneis","Medieval Bestiaries","Remora, said to attach to ships to slow them down"])
db.append(["Edimmu","Sumerian","Ghosts of those not buried properly"])
db.append(["Egbere","Yoruba","Humanoid that carries a magical mat"])
db.append(["Einherjar","Norse","Spirits of brave warriors"])
db.append(["Ekek","Philippine","Flesh-eating, winged humanoids"])
db.append(["Elbow Witch","Ojibwa","Hags with awls in their elbows"])
db.append(["Eldjötnar","Norse","the Fire Giants who reside in Muspelheim, with Surtr as their leader"])
db.append(["Eleionomae","Greek","Marsh nymph"])
db.append(["Elemental","Alchemy","Personification of one of the Classical elements"])
db.append(["‘Elepaio","Hawaiian","Monarch flycatcher spirit that guides canoe-builders to the proper trees"])
db.append(["Elf","Germanic","Nature and fertility spirit"])
db.append(["Eloko","Central Africa","Little people and malevolent nature spirits"])
db.append(["Emela-ntouka","Central Africa","Gigantic, elephant-killing beast"])
db.append(["Emere","Yoruba","Child that can move back and forth between the material world and the afterlife at will"])
db.append(["Emim","Jewish","Giant"])
db.append(["Empusa","Greek","Female demon that waylays travelers and seduces and kills men"])
db.append(["Encantado","Brazilian","Dolphin-human shapeshifter"])
db.append(["Enchanted Moor","Portuguese","Enchanted princesses"])
db.append(["Enfield","Heraldic","Fox-greyhound-lion-wolf-eagle hybrid"])
db.append(["Engkanto","Philippine","neutral nature spirit"])
db.append(["Enkō","Japanese","Kappa of Shikoku and western Honshū"])
db.append(["Epimeliad","Greek","Apple tree nymph"])
db.append(["Erchitu","Sardinia","Ox-human, wereox"])
db.append(["Er Gui","Chinese","Hungry ghost"])
db.append(["Erinyes","Greek","possibly winged spirits of vengeance or justice. Also known as Furies."])
db.append(["Erlking","German","Death spirit"])
db.append(["Erymanthian Boar","Greek","Giant boar"])
db.append(["Ethiopian Pegasus","Medieval Bestiaries","Two-horned, winged horse"])
db.append(["Ettin","English","Three-headed giant"])
db.append(["Eurynomos","Greek","Blue-black, carrion-eater in the underworld"])
db.append(["Ewah","Cherokee","Human-cougar hybrid"])
db.append(["Ežerinis","Lithuanian","Lake spirit"])
db.append(["Fachen","Irish and Scottish","Monster with half a body"])
db.append(["Fairy","Many cultures worldwide","Nature spirits"])
db.append(["Familiar","English","Animal servant"])
db.append(["Far darrig","Irish","Little people that constantly play pranks"])
db.append(["Faun","Roman","Human-goat hybrid nature spirit"])
db.append(["Fear gorta","Irish","Hunger ghost"])
db.append(["Feathered Serpent","Mesoamerican","dragon"])
db.append(["Fenghuang","Chinese","Chinese Phoenix, female in marriage symbol"])
db.append(["Fenodyree","Manx","House spirit"])
db.append(["Fenrir","Norse","Gigantic, ravenous wolf"])
db.append(["Fetch","Irish","Double or doppelgänger"])
db.append(["Fext","Slavic","Undead"])
db.append(["Finfolk","Orkney","Fish-human hybrid that kidnaps humans for servants"])
db.append(["Fir Bolg","Irish","Ancestral race"])
db.append(["Fire Bird","Many cultures worldwide","Regenerative, solar bird"])
db.append(["Firedrake","Germanic","Dragon"])
db.append(["Fish-man","Cantabrian","Amphibious, scaled humanoid"])
db.append(["Fomorian","Irish","Goat-headed giant"])
db.append(["Forest Bull","Medieval Bestiaries","Giant, red cattle with swiveling horns"])
db.append(["Freybug","Norfolk","black dog"])
db.append(["Fuath","Celtic","Malevolent water spirit"])
db.append(["Fucanglong","Chinese","Underworld dragon"])
db.append(["Funayūrei","Japanese","Ghosts of people who drowned at sea"])
db.append(["Furu-utsubo","Japanese","Animated jar"])
db.append(["Futakuchi-onna","Japanese","Woman with a second mouth on the back of her head"])
db.append(["Fylgja","Scandinavian","Animal familiar"])
db.append(["Gaasyendietha","Seneca","Dragon"])
db.append(["Gagana","Russian","Bird with iron beak and copper talons"])
db.append(["Gaki","Japanese","Ghosts of especially greedy people"])
db.append(["Gallu","Mesopotamian","Underworld demons"])
db.append(["Galtzagorriak","Basque","Diminutive, demonic servants"])
db.append(["Gamayun","Russian","Prophetic bird with human head"])
db.append(["Gana","Hindu","Attendants of Shiva"])
db.append(["Gancanagh","Irish","Male fairy that seduces human women"])
db.append(["Gandaberunda","Hindu","Double-headed bird"])
db.append(["Gandharva","Hindu","Male nature spirits, often depicted as part human, part animal"])
db.append(["Gargouille","French","Water dragon"])
db.append(["Garmr","Norse","Giant, ravenous hound"])
db.append(["Garuda","Hindu","Human-eagle hybrid"])
db.append(["Gashadokuro","Japanese","Giant, malevolent skeletons"])
db.append(["Gaueko","Basque","Wolf capable of walking upright"])
db.append(["Ged","Heraldic","The fish pike"])
db.append(["Gegenees","Greek","Six-armed giant"])
db.append(["Genie","Arabian","Elemental spirit"])
db.append(["Genius loci","Roman","Spirit that protects a specific place"])
db.append(["German","Slavic","Male spirit associated with bringing rain and hail"])
db.append(["Geryon","Greek","Giant with three heads, six arms, three torsos and (in some sources) six legs"])
db.append(["Ghillie Dhu","Scottish","Tree guardian"])
db.append(["Ghost","--","Disembodied spirits, specifically of those that have died"])
db.append(["Ghoul","Arabian","Earth genie. Also a shape shifting desert anthropophagus, often classified as undead."])
db.append(["Giant animal","Worldwide","Unusually large beasts"])
db.append(["Giant","Worldwide","Humanoid creatures of immense size and strength"])
db.append(["Gichi-anami'e-bizhiw","Ojibwa","Bison-snake-bird-cougar hybrid and water spirit"])
db.append(["Gidim","Sumerian","Ghost"])
db.append(["Gigantes","Greek","Race of giants that fought the Olympian gods, sometimes depicted with snake-legs"])
db.append(["Gigelorum","Scottish","Smallest animal"])
db.append(["Girtablilu","Akkadian","Human-scorpion hybrid"])
db.append(["Gjenganger","Scandinavian","Corporeal ghost"])
db.append(["Glaistig","Scottish","Human-goat hybrid"])
db.append(["Glashtyn","Manx","Malevolent water horse"])
db.append(["Gnome","Alchemy","Diminutive Earth elemental"])
db.append(["Goblin","Medieval","Grotesque, mischievous little people"])
db.append(["Gog","English","Giant protector of London"])
db.append(["Gold-digging ant","Medieval Bestiaries","Dog-sized ant that digs for gold in sandy areas"])
db.append(["Golem","Jewish","Animated construct"])
db.append(["Gorgades","Medieval Bestiary","Hairy humanoid"])
db.append(["Gorgon","Greek","Fanged, snake-haired humanoids that turn anyone who sees them into stone"])
db.append(["Goryō","Japanese","Vengeful ghosts, usually of martyrs"])
db.append(["Grassman","Ohio, USA","Ape-like cryptid"])
db.append(["Gremlin","Folklore","Goblins that sabotage airplanes"])
db.append(["Griffin","Heraldic","Lion-eagle hybrid"])
db.append(["Grigori","Christian","Fallen angels"])
db.append(["Grim","English and Scandinavian","Tutelary spirits of churches"])
db.append(["Grindylow","English","Malevolent water spirit"])
db.append(["Grine","Moroccan","Genie duplicate of a person. Lives in a parallel world"])
db.append(["Gualichu","Mapuche","Malevolent spirit"])
db.append(["Gud-elim","Akkadian","Human-bull hybrid"])
db.append(["Guhin","Japanese","Anthropomorphic bird"])
db.append(["Gui Po","Chinese","Ghost that manifests as an old woman"])
db.append(["Gui Shu","Chinese","Ghostly tree that confuses travelers by moving"])
db.append(["Gulon","Germanic","Gluttonous dog-cat-fox hybrid"])
db.append(["Gumiho","Korean mythology","A demon fox with thousands of tails. Believed to possess an army of spirits and magic in its tails."])
db.append(["Gurumapa","Nepalese","Child-eating demon"])
db.append(["Gwyllgi","Welsh","black dog"])
db.append(["Gwyllion","Welsh","Malevolent spirit"])
db.append(["Gyascutus","American folklore","Four-legged herbivore"])
db.append(["Gytrash","Lincolnshire and Yorkshire","black dog"])
db.append(["Gyūki","Japanese","Bull-headed monster"])
db.append(["Habrok","Norse","the 'best' hawk"])
db.append(["Hadhayosh","Persian","Gigantic land animal"])
db.append(["Haetae","Korean","Dog-lion hybrid"])
db.append(["Hag","Many cultures worldwide","Wizened old woman, usually a malevolent spirit with this specific form, or a goddess in disguise"])
db.append(["Haietlik","Nuu-chah-nulth","Water serpent"])
db.append(["Hai-uri","Khoikhoi","Male, anthropophagous, partially invisible monster"])
db.append(["Hakutaku","Japanese","Talking beast which handed down knowledge on harmful spirits"])
db.append(["Hākuturi","Māori","Nature guardian"])
db.append(["Half-elf","Norse","Hybrid of a human and an elf."])
db.append(["Haltija","Finnish","Spirit that protects a specific place"])
db.append(["Hamadryad","Greek","Oak tree nymph"])
db.append(["Hamingja","Scandinavian","Personal protection spirit"])
db.append(["Hamsa","Buddhist, Hindu, and Jainism","Mystical bird"])
db.append(["Hanau epe","Rapa Nui","Long-eared humanoid"])
db.append(["Hantu Air","Malay","Shapeshifting water spirit"])
db.append(["Hantu Demon","Philippine","Demon"])
db.append(["Hantu Raya","Malay","Demonic servant"])
db.append(["Harionago","Japanese","Humanoid female with barbed, prehensile hair"])
db.append(["Harpy","Greek","Death spirit with the form of a bird with a human head"])
db.append(["Haugbui","Norse","Undead who cannot leave its burial mound"])
db.append(["Havsrå","Norse","Saltwater spirit"])
db.append(["Headless Horseman","European","Humanoid spirit who haunts or kills"])
db.append(["Headless Mule","Brazilian","Fire-spewing, headless, spectral mule"])
db.append(["Hecatonchires","Greek","Primordial giants with 100 hands and fifty heads"])
db.append(["Heikegani","Japanese","Crabs with human-faced shells, the spirits of the warriors killed in the Battle of Dan-no-ura"])
db.append(["Heinzelmännchen","German","Household spirit"])
db.append(["Helead","Greek","Fen nymph"])
db.append(["Hellhound","Many cultures worldwide","Dog from underworld"])
db.append(["Heracles","Greek","Gatekeeper of Olympus"])
db.append(["Hercinia","Medieval Bestiaries","Glowing bird"])
db.append(["Herensuge","Basque","Dragon"])
db.append(["Hesperides","Greek","Nymph daughters of Atlas"])
db.append(["Hidebehind","United States","Nocturnal forest creature"])
db.append(["Hiderigami","Japanese","Drought spirit"])
db.append(["Hieracosphinx","Ancient Egypt","Falcon-headed sphinx"])
db.append(["Hihi","Japanese","Baboon monster"])
db.append(["Hiisi","Finnish","Nature guardian"])
db.append(["Hippocamp","Etruscan, Greek, and Phoenician","Horse-fish hybrid"])
db.append(["Hippogriff","Medieval Bestiaries","Hybrid of a griffin and horse, that is a lion-eagle-horse hybrid"])
db.append(["Hippopodes","Medieval Bestiary","Horse-hoofed humanoid"])
db.append(["Hircocervus","Medieval Bestiary","Deer-goat hybrid"])
db.append(["Hitodama","Japanese","Ghosts of the newly dead, which take the form of fireballs"])
db.append(["Hitotsume-kozō","Japanese","One-eyed childlike spirit"])
db.append(["Hobbididance","English","Malevolent spirit"])
db.append(["Hob","English","House spirit"])
db.append(["Hobgoblin","Medieval","Friendly or amusing goblin"])
db.append(["Hodag","Native American","part frog, part mammoth, part lizard, from Native American mythology"])
db.append(["Hokhokw","Kwakiutl","a bird"])
db.append(["Hōkō","Japanese","Dog-like tree spirit from China"])
db.append(["Homa","Persian","Eagle-lion hybrid, similar to a griffin"])
db.append(["Hombre Caiman","Colombian","Human-alligator hybrid"])
db.append(["Hombre Gato","Latin America","Human-cat hybrid"])
db.append(["Homunculus","Alchemy","Diminutive, animated construct"])
db.append(["Hō-ō","Japanese","Rooster-swallow-fowl-snake-goose-tortoise-stag-fish hybrid"])
db.append(["Hoopoe","Africa","A near passerine bird common to Africa and Eurasia that features in many mythologies in those continents"])
db.append(["Horned Serpent","Native American","Serpentine rain spirit"])
db.append(["Hotoke","Japanese","Deceased person"])
db.append(["Houri","Islamic","Heavenly beings"])
db.append(["Hraesvelg","Norse","a giant, who in eagle form, creates the wind by beating his wings"])
db.append(["Hrímþursar","Norse","Frost Giants who are the main inhabitants of either Jotunheim or Niflheim"])
db.append(["Huaychivo","Mayan","Human-deer hybrid"])
db.append(["Hugin and Munin","Norse","Thought and Memory; a pair of ravens associated with the Norse god Odin"])
db.append(["Huldra","Scandinavian","Forest spirit"])
db.append(["Huli jing","Chinese","Nine-tailed fox spirit"])
db.append(["Huma","Persian","Regenerative fire bird"])
db.append(["Humbaba","Akkadian","Lion-faced giant"])
db.append(["Hundun","Chinese","Chaos spirit"])
db.append(["Hupia","Taíno","Nocturnal ghost"])
db.append(["Hyakume","Japanese","Creature with a hundred eyes"])
db.append(["Hydra","Greek","Multi-headed water serpent/dragon"])
db.append(["Hydros","Medieval Bestiary","Snake whose poison causes the victim to swell up"])
db.append(["Hydrus","Medieval Bestiary","Snake from the Nile River that would kill crocodiles from the inside"])
db.append(["Hyōsube","Japanese","Hair-covered kappa"])
db.append(["Hypnalis","Medieval Bestiary","Snake that kills its victims in their sleep"])
db.append(["Iannic-ann-ôd","Breton","Ghost of a drowned person"])
db.append(["Iara","Brazilian","Female water spirit"])
db.append(["Ibong Adarna","Philippine","Bird that changes color each time it finishes a song"])
db.append(["Ichchhadhari Nag","Hindu","shape-shifting venomous snakes"])
db.append(["Ichimoku-nyūdō","Japanese","One-eyed kappa from Sado Island"])
db.append(["Ichiren-Bozu","Japanese","Animated prayer beads"])
db.append(["Ichneumon","Medieval Bestiaries","Dragon-killing animal"])
db.append(["Ichthyocentaur","Greek","Human-fish-horse hybrid"])
db.append(["Iele","Romanian","Female nature spirits"])
db.append(["Ifrit","Arabian","Fire genie"])
db.append(["Ijiraq","Inuit","Spirit that kidnaps children"])
db.append(["Ikiryō","Japanese","can be considered a 'living ghost', as it is a person's spirit outside their body"])
db.append(["Ikuchi","Japanese","Sea-serpent that travels over boats in an arc while dripping oil"])
db.append(["Iku-Turso","Finnish","Sea monster"])
db.append(["Il-Belliegħa","Maltese","Malevolent well spirit"])
db.append(["Imp","Medieval","Diminutive, demonic servant"])
db.append(["Impundulu","Southern Africa","Avian, vampiric lightning spirit"])
db.append(["Imugi","Korean","Flightless, dragon-like creatures (sometimes thought of as proto-dragons)"])
db.append(["Inapertwa","Aboriginal","Simple organisms, used by creator-gods to make everything else"])
db.append(["Incubus","Medieval folklore","Male night-demon and rapist"])
db.append(["Indrik","Russian","One-horned horse-bull hybrid"])
db.append(["Indus Worm","Medieval Bestiaries","Giant, white, carnivorous worm"])
db.append(["Inkanyamba","Zulu","Horse-headed serpent"])
db.append(["Inugami","Japanese","Dog spirit"])
db.append(["Ipotane","Greek","Horse-human hybrid, two-legged (as opposed to the four-legged centaur)"])
db.append(["Ippon-datara","Japanese","One-legged mountain spirit"])
db.append(["Iratxoak","Basque","Diminutive, demonic servants"])
db.append(["Irin","Jewish","Fallen angels"])
db.append(["Ishigaq","Inuit","Little people"])
db.append(["Island Satyr","Medieval Bestiaries","Savage human-goat hybrid from a remote island chain"])
db.append(["Isonade","Japanese","Shark-like sea monster"])
db.append(["Ittan-momen","Japanese","Ghostly aerial phenomenon that attacks people"])
db.append(["Iwana-bōzu","Japanese","Char which appeared as a Buddhist monk"])
db.append(["Jackalope","American","A rabbit with antlers"])
db.append(["Jack-In-Irons","English","Malevolent giant"])
db.append(["Jaculus","Medieval Bestiaries","Winged serpent or small dragon"])
db.append(["Jasconius","Medieval folklore","Island-sized fish"])
db.append(["Jasy Jaterei","Guaraní","Nature guardian and bogeyman"])
db.append(["Jatayu","Hindu mythology","A demi-god who has the form of a vulture"])
db.append(["Jaud","Slavic","Vampirised premature baby"])
db.append(["Jenglot","Java","Vampiric little people"])
db.append(["Jengu","Sawa","Water spirit"])
db.append(["Jentil","Basque","Megalith-building giant"])
db.append(["Jenu","Mi'kmaq","Anthropophagous giant"])
db.append(["Jerff","Swedish","Gluttonous dog-cat-fox hybrid"])
db.append(["Jersey Devil","American","Demonic dragon that was given birth to by an American living in New Jersey"])
db.append(["Jian","Chinese","One-eyed, one-winged bird who requires a mate for survival"])
db.append(["Jiangshi","Chinese","Life-draining, reanimated corpse"])
db.append(["Jiaolong","Chinese","Dragon"])
db.append(["Jibakurei","Japanese","Spirit that protects a specific place"])
db.append(["Jievaras","Lithuanian","House spirit"])
db.append(["Jikininki","Japanese","Corpse-eating ghost"])
db.append(["Jinn","Arabian","Spiritual creatures"])
db.append(["Jiufeng","Chinese","a nine-headed bird worshiped by ancient natives in Hubei Province."])
db.append(["Jiu tou niao","Chinese","Nine-headed, demonic bird"])
db.append(["Jogah","Iroquois","Little people nature spirit"])
db.append(["Jörmungandr","Norse","Sea serpent"])
db.append(["Jorōgumo","Japanese","Spider woman"])
db.append(["Jotai","Japanese","Animated folding screen cloth"])
db.append(["Jötunn","Norse","Gigantic nature spirits"])
db.append(["Jujak","Korean","A bird"])
db.append(["Jumbee","Guyanese","Malevolent spirit"])
db.append(["Kabouter","Dutch","Little people that live underground, in mushrooms, or as house spirits"])
db.append(["Kachina","Hopi and Puebloan","Nature spirit"])
db.append(["Kahaku","Japanese","Little people and water spirits"])
db.append(["Kajsa","Scandinavian","Wind spirit"])
db.append(["Kalakeyas","Hindu","Descendents of Kala"])
db.append(["Kallikantzaroi","Greek","Grotesque, malevolent spirit"])
db.append(["Kamaitachi","Japanese","Wind spirit"])
db.append(["Kami","Japanese","Nature spirit"])
db.append(["Kamikiri","Japanese","Hair-cutting spirit"])
db.append(["Kanbari-nyūdō","Japanese","Bathroom spirit"])
db.append(["Kanbo","Japanese","Drought spirit"])
db.append(["Kanedama","Japanese","Money spirit"])
db.append(["Kappa","Japanese","Little people and water spirits"])
db.append(["Kapre","Philippine","Malevolent tree spirit"])
db.append(["Karakoncolos","Bulgarian and Turkish", "also in Bosnia and Herzegovina and Serbia known as Karanđoloz- Troublesome spirit"])
db.append(["Karakura","Turkish","Male night-demon"])
db.append(["Karasu-tengu","Japanese","Tengu with a bird's bill"])
db.append(["Karkadann","Persian","One-horned giant animal"])
db.append(["Karkinos","Greek","Giant crab"])
db.append(["Karura","Japanese","Eagle-human hybrid"])
db.append(["Karzełek","Polish","Little people and mine spirits"])
db.append(["Kasa-obake","Japanese","Animated parasol"])
db.append(["Kasha","Japanese","Cat-like demon which descends from the sky and carries away corpses"])
db.append(["Kashanbo","Japanese","Kappa who climb into the mountains for the winter"])
db.append(["Katawa-guruma","Japanese","Woman riding on a flaming wheel"])
db.append(["Katsura-otoko","Japanese","Handsome man from the moon"])
db.append(["Kaukas","Lithuanian","Nature spirit"])
db.append(["Kawa-uso","Japanese","Supernatural river otter"])
db.append(["Kawa-zaru","Japanese","Smelly, cowardly water spirit"])
db.append(["Keelut","Inuit","Hairless dog"])
db.append(["Kee-wakw","Abenaki","Anthropophagous giant"])
db.append(["Kekkai","Japanese","Amorphous afterbirth spirit"])
db.append(["Kelpie","Irish and Scottish","Malevolent water horse"])
db.append(["Ker","Greek","Female death spirit"])
db.append(["Kesaran-pasaran","Japanese","Mysterious, white, fluffy creature"])
db.append(["Keukegen","Japanese","Disease spirit"])
db.append(["Keythong","Heraldic","Wingless griffin"])
db.append(["Khalkotauroi","Greek","Bronze-hoofed bulls"])
db.append(["Khyah","Nepalese","Fat, hairy ape-like creature"])
db.append(["Kigatilik","Inuit","Night-demon"])
db.append(["Kijimunaa","Japanese","Tree sprite from Okinawa"])
db.append(["Kijo","Japanese","She-devil"])
db.append(["Kikimora","Slavic","Female house spirit"])
db.append(["Killmoulis","English and Scottish","Ugly, mischievous mill spirit"])
db.append(["Kinnara","Hindu","Human-bird hybrid"])
db.append(["Kin-u","Japanese","a bird"])
db.append(["Kirin","Japanese","Japanese Unicorn"])
db.append(["Kishi","Angola","Malevolent, two-faced seducer"])
db.append(["Kitsune","Japanese","Fox spirit"])
db.append(["Kitsune-Tsuki","Japanese","Person possessed by a fox spirit"])
db.append(["Kiyohime","Japanese","Woman who transformed into a serpent-demon out of the rage of unrequited love"])
db.append(["Klabautermann","German","Ship spirit"])
db.append(["Knocker","folklore)","Cornish and Welsh","Little people and mine spirits"])
db.append(["Knucker","English","Water dragon"])
db.append(["Kobalos","Greek","Shape-shifting thieves and tricksters"])
db.append(["Kobold","German","Little people and mine or house spirits"])
db.append(["Kodama","Japanese","Tree spirit"])
db.append(["Kofewalt","Germanic","House spirit"])
db.append(["Ko-gok","Abenaki","Hideous monster"])
db.append(["Kokakuchō","Japanese","Ubume bird"])
db.append(["Komainu","Japanese","Protective animal"])
db.append(["Konaki-Jijii","Japanese","Infant that cries until it is picked up, then increases its weight and crushes its victim"])
db.append(["Kongamoto","Congo","Flying creature"])
db.append(["Konoha-tengu","Japanese","Anthropomorphic bird"])
db.append(["Koro-pok-guru","Ainu","Little people"])
db.append(["Korrigan","Breton","Little people and nature spirits"])
db.append(["Kraken","Scandinavian","Sea monster"])
db.append(["Krasnoludek","Slavic","Little people nature spirits"])
db.append(["Krasue","Southeast Asian","Vampiric, floating head"])
db.append(["Kuarahy Jára","Guaraní","Forest spirit"])
db.append(["Kubikajiri","Japanese","Female corpse-chewing graveyard spirit"])
db.append(["Kuchisake-onna","Japanese","Vengeful ghost of a woman mutilated by her husband"])
db.append(["Kuda-gitsune","Japanese","Miniature fox spirit"])
db.append(["Kudan","Japanese","Human-faced calf which predicts a calamity and then dies"])
db.append(["Kui","Chinese","One-legged monster"])
db.append(["Kulshedra","Albanian","Drought-causing dragon"])
db.append(["Kumakatok","Philippine","Death spirits"])
db.append(["Kumiho","Korean","Fox spirit"])
db.append(["Kun","Chinese","Giant fish"])
db.append(["Kupua","Hawaiian","Shapeshifting tricksters"])
db.append(["Kurabokko","Japanese","Guardian spirit of a warehouse"])
db.append(["Kurage-no-hinotama","Japanese","Jellyfish which floats through the air as a fireball"])
db.append(["Kurma","Hindu mythology","the second avatar of Vishnu in the form of a Turtle"])
db.append(["Kurupi","Guaraní","Wild man and fertility spirit"])
db.append(["Kushtaka","Tlingit","Shapeshifting otter spirit"])
db.append(["Kwakwakalanooksiwae","Kwakiutl","a bird"])
db.append(["Kye-ryong","Korean","Chicken-lizard hybrid"])
db.append(["Kyourinrin","Japanese","Animated scroll or paper"])
db.append(["Kyūbi-no-kitsune","Japanese","Nine-tailed fox"])
db.append(["Kyūketsuki","Japanese","Vampire"])
db.append(["La-bar-tu","Assyrian","Disease demon"])
db.append(["Labbu","Akkadian","Sea snake"])
db.append(["Ladon","Greek","Dragon guarding the golden apples of the Hesperides"])
db.append(["Lady midday","Slavic","Sunstroke spirit"])
db.append(["Laelaps","Greek","Enchanted dog that always caught his prey"])
db.append(["Laestrygonians","Greek","Anthropophagic giants"])
db.append(["Lakanica","Slavic","Field spirit"])
db.append(["Lake monster","Worldwide","Gigantic animals reputed to inhabit various lakes around the world"])
db.append(["Lakhey","Nepalese","Demon with fangs"])
db.append(["La Llorona","Latin America","Death spirit associated with drowning"])
db.append(["Lamassu","Akkadian and Sumerian","Protective spirit with the form of a winged bull or lion with a human head"])
db.append(["Lambton Worm","English","Giant worm"])
db.append(["Lamia","Greek","Child-devouring monster"])
db.append(["Lamiak","Basque","Water spirit with bird feet"])
db.append(["La Mojana","Colombian","Shapeshifting, female water spirit"])
db.append(["Lampades","Greek","Underworld nymph"])
db.append(["Landvættir","Norse","Nature spirits"])
db.append(["Lares","Roman","House spirit"])
db.append(["La Sayona","Venezuela","Female ghost that punishes unfaithful husbands"])
db.append(["La Tunda","Colombian","Nature spirit that seduces and kills men"])
db.append(["Laukų dvasios","Lithuanian","Field spirit"])
db.append(["Lauma","Baltic","Sky spirit"])
db.append(["Lavellan","Scottish","Gigantic water rat"])
db.append(["Leanan sidhe","Celtic","Fairy lover"])
db.append(["Leanashe","Irish","Possessing spirit or vampire"])
db.append(["Leimakids","Greek","Meadow nymph"])
db.append(["Leokampoi","Etruscan","Fish-tailed lion"])
db.append(["Leontophone","Medieval Bestiary","Tiny animal poisonous to lions"])
db.append(["Leprechaun","Irish","Cobbler spirit"])
db.append(["Leszi","Slavic","Tree spirit"])
db.append(["Leuce","Greek","White poplar tree nymph"])
db.append(["Leucrota","Medieval Bestiary","Hybrid of a lion and crocotta"])
db.append(["Leviathan","Jewish","Sea monster, as seen in Job 41"])
db.append(["Leyak","Balinese","Anthropophagous flying head with entrails"])
db.append(["Libyan Aegipanes","Medieval Bestiaries","Human-horse hybrid"])
db.append(["Libyan Satyr","Medieval Bestiaries","Human-goat hybrid"])
db.append(["Lidérc","Hungary","Magical chicken that transforms into a humanoid"])
db.append(["Lightning Bird","Southern Africa","Magical bird that can be found at sites of lightning strikes"])
db.append(["Likho","Slavic","One-eyed hag or goblin"])
db.append(["Lilin","Jewish","Night-demoness"])
db.append(["Lilitu","Assyrian","Winged demon"])
db.append(["Limnades","Greek","Lake nymph"])
db.append(["Lindworm","Germanic","Dragon"])
db.append(["Ljósálfar","Norse","Sunlight spirits; the Light Elves"])
db.append(["Llamhigyn Y Dwr","Welsh","Frog-bat-lizard hybrid"])
db.append(["Lo-lol","Abenaki","Hideous monster"])
db.append(["Longana","Italian","Female human-goat hybrid and water spirit"])
db.append(["Lóng","Chinese","dragon"])
db.append(["Long Ma","Chinese","Dragon-horse hybrid"])
db.append(["Loogaroo","French America","Shapeshifting, female vampire"])
db.append(["Lou Carcolh","French","Snake-mollusk hybrid"])
db.append(["Loup-garou","French","Werewolf"])
db.append(["Lubber fiend","English","House spirit"])
db.append(["Luduan","Chinese","Truth-detecting animal"])
db.append(["Luison","Guaraní","Death spirit"])
db.append(["Lutin","French","Amusing goblin"])
db.append(["Lynx","Medieval Bestiaries","Feline guide spirit"])
db.append(["Maa-alused","Estonian mythology","Subterranean spirit"])
db.append(["Maal","Bengali mythology","Malevolent ghostly mermaid."])
db.append(["Machlyes","Medieval bestiaries","Hermaphroditic humanoid"])
db.append(["Macrocephali","Medieval bestiaries","Giant-headed humanoid"])
db.append(["Madremonte","Colombian folklore","Nature guardian"])
db.append(["Maero","Māori","Savage, arboreal humanoids"])
db.append(["Magog","English folklore","Giant protector of London"])
db.append(["Maha-pudma","Hindu mythology","Giant elephant that holds up the world"])
db.append(["Mairu","Basque mythology","Megalith-building giant"])
db.append(["Mājas gari","Latvian mythology","Benevolent house spirit"])
db.append(["Makara","Indian mythology","Aquatic beings"])
db.append(["Makura-gaeshi","Japanese mythology","Pillow-moving spirit"])
db.append(["Mallt-y-Nos","Welsh mythology","Spirit of the hunt"])
db.append(["Mami Wata","Africa and the African diaspora","Supernaturally beautiful water spirits"])
db.append(["Manananggal","Philippine mythology","Vampires that sever their torsos from their legs to fly around"])
db.append(["Mandi","Medieval bestiaries","Humanoid with a forty-year lifespan"])
db.append(["Mandrake","Medieval folklore","Diminutive, animated construct"])
db.append(["Manes","Roman mythology","Ancestral spirits"])
db.append(["Mannegishi","Cree","Little people with six fingers and no noses"])
db.append(["Manticore","Persian mythology","Lion-human-scorpion hybrid"])
db.append(["Mapinguari","Brazilian mythology","Giant sloth"])
db.append(["Marabbecca","Italian folklore","Malevolent water spirit"])
db.append(["Mara","Scandinavian folklore","Female night-demon"])
db.append(["Mareikura","Tuamotu","Attendant of Kiho-tumu, the supreme god"])
db.append(["Mares of Diomedes","Greek mythology","Man-eating horses"])
db.append(["Marid","Arabian mythology","Jinn associated with open waters of the seas and oceans"])
db.append(["Maro deivės","Lithuanian mythology","Disease spirits"])
db.append(["Maski-mon-gwe-zo-os","Abenaki mythology","Shapeshifting toad spirit"])
db.append(["Matagot","French mythology","Spirit that takes animal form; usually that of a black cat"])
db.append(["Matsya","Hindu mythology","first Avatar of Vishnu in the form of a half-fish and half-man"])
db.append(["Mayura","Hindu mythology","Peacock spirit"])
db.append(["Mazikeen","Jewish mythology","Invisible, malevolent spirit"])
db.append(["Mbói Tu'ĩ","Guaraní mythology","Snake-parrot hybrid"])
db.append(["Mbwiri","Central Africa","Possessing demon"])
db.append(["Meliae","Greek mythology","Ash tree nymph"])
db.append(["Melusine","Medieval folklore","Female water spirit, with the form of a winged mermaid or serpent"])
db.append(["Menehune","Hawaiian mythology","Little people and craftsmen"])
db.append(["Menninkäinen","Finnish mythology","Little people and nature spirits"])
db.append(["Merlion","Singapore","Combination of a lion and a fish, the symbol of Singapore"])
db.append(["Mermaid","multiple cultures","Human-fish hybrid"])
db.append(["Merrow","Irish mythology and Scottish","Human-fish hybrid"])
db.append(["Metee-kolen-ol","Abenaki mythology","Ice-hearted wizards"])
db.append(["Mimi","Australian Aboriginal mythology","Extremely elongated humanoid that has to live in rock crevasses to avoid blowing away"])
db.append(["Minka Bird","Australian Aboriginal mythology","Death spirit"])
db.append(["Minokawa","Philippine","Giant swallow"])
db.append(["Minotaur","Greek mythology","Human-bull hybrid"])
db.append(["Mishibizhiw","Ojibwa","Feline water spirit"])
db.append(["Misi-ginebig","Ojibwa","Serpentine rain spirit"])
db.append(["Misi-kinepikw","Cree","Serpentine rain spirit"])
db.append(["Mizuchi","Japanese mythology","Water dragon"])
db.append(["Mngwa","Tanzania","Gigantic, ferocious nocturnal feline"])
db.append(["Mogwai","Chinese mythology","Vengeful ghost or demon"])
db.append(["Mohan","Latin American folklore","Nature spirit"])
db.append(["Mokèlé-mbèmbé","Congo","Water-dwelling creature"])
db.append(["Mokoi","Australian Aboriginal mythology","Malevolent spirit that kills sorcerers"])
db.append(["Monocerus","Medieval bestiaries","One-horned stag-horse-elephant-boar hybrid, sometimes treated as distinct from the unicorn"])
db.append(["Mono Grande","South America","Giant monkey"])
db.append(["Monopod","Medieval bestiaries","Dwarf with one giant foot"])
db.append(["Moñái","Guaraní mythology","Giant snake with antennae"])
db.append(["Mooinjer veggey","Manx folklore","Nature spirit"])
db.append(["Mora","Slavic mythology","Disembodied spirit"])
db.append(["Morgens","Breton and Welsh mythology","Water spirits"])
db.append(["Morinji-no-okama","Japanese mythology","Animated tea kettle"])
db.append(["Mormolykeia","Greek","Underworld spirit"])
db.append(["Moroi","Romanian","Vampiric ghost"])
db.append(["Moss people","Continental Germanic mythology","Little people and tree spirits"])
db.append(["Mrenh Gongveal { Khmer: ម្រេញគង្វាល }","Cambodian folklore","Elf"])
db.append(["Mujina","Japanese mythology","Shapeshifting badger spirit"])
db.append(["Muldjewangk","Australian Aboriginal mythology","Water monster"])
db.append(["Muma Pădurii","Romanian folklore","Forest-dwelling hag"])
db.append(["Muscaliet","Medieval bestiaries","Extremely hot hare-squirrel-boar hybrid"])
db.append(["Muse","Greek mythology","Spirits that inspire artists"])
db.append(["Musimon","Heraldic","Sheep-goat hybrid"])
db.append(["Myling","Scandinavian folklore","Ghosts of unbaptized children"])
db.append(["Myrmecoleon","Medieval bestiaries","Ant-lion hybrid"])
db.append(["Nachzehrer","German","Anthropophagous undead"])
db.append(["Nāga","Buddhist and Hindu","Nature and water spirits, serpentine or human-serpent hybrids"])
db.append(["Naga fireballs","Thai","Spectral fire"])
db.append(["Nagual","Mesoamerica","Human-animal shapeshifter"])
db.append(["Naiad","Greek","Freshwater nymph"])
db.append(["Näkki","Finnish","Water spirit"])
db.append(["Namahage","Japanese","Ritual disciplinary demon from the Oga Peninsula"])
db.append(["Namazu","Japanese","Giant catfish whose thrashing causing earthquakes"])
db.append(["Nando-baba","Japanese","Old woman who hides under the floor in abandoned storerooms"])
db.append(["Nang Takian","Thai","Tree spirit"])
db.append(["Nanom-keea-po-da","Abenaki","Earthquake spirit"])
db.append(["Napaeae","Greek","Grotto nymph"])
db.append(["Narasimha","Hindu mythology","Avatar of Vishnu in the form of half-man/half-lion"])
db.append(["Narecnitsi","Slavic","Fate spirit"])
db.append(["Nargun","Gunai","Water monster"])
db.append(["Nariphon","Thai","Pod people"])
db.append(["Nasnas","Arabian","Half-human, half-demon creature with half a body"])
db.append(["Nav'","Slavic","Ghost"])
db.append(["Nawao","Hawaiian","Savage humanoid"])
db.append(["N-dam-keno-wet","Abenaki","Fish-human hybrid"])
db.append(["Neck","Germanic mythology","Female water spirit"])
db.append(["Negret","Catalan","Little people that turn into coins"])
db.append(["Nekomata","Japanese","Split-tailed magical cat"])
db.append(["Nekomusume","Japanese","Cat in the form of a girl"])
db.append(["Nemean Lion","Greek","Lion with impenetrable skin"])
db.append(["Nephilim","Jewish","Giant"])
db.append(["Nereid","Greek","Nymph daughters of Nereus"])
db.append(["Ngen","Mapuche","Nature spirit"])
db.append(["Nguruvilu","Mapuche","Fox-like water snake"])
db.append(["Nian","Chinese","Predatory animal"])
db.append(["Níðhöggr","Norse","Dragon"])
db.append(["Nightmarchers","Hawaiian","Warrior ghosts"])
db.append(["Nikusui","Japanese","Monster which appears as a young woman and sucks all of the flesh off of its victim's body"])
db.append(["Nimerigar","Shoshone","Aggressive little people"])
db.append(["Ningyo","Japanese","Monkey-fish hybrid"])
db.append(["Ninki Nanka","Western Africa","Large reptile, possibly a dragon"])
db.append(["Nisse","Scandinavian","House spirit"])
db.append(["Nivatakavachas","Hindu","Ocean demon"])
db.append(["Nix","Germanic","Female water spirit"])
db.append(["Nobusuma","Japanese","Supernatural wall. Also a monstrous flying squirrel"])
db.append(["Nocnitsa","Slavic","Nightmare spirit"])
db.append(["Noppera-bō","Japanese","Faceless ghost"])
db.append(["Nozuchi","Japanese","Small sea serpent"])
db.append(["Nuckelavee","Scottish","Malevolent human-horse-fish hybrid"])
db.append(["Nue","Japanese","Monkey-raccoon dog-tiger-snake hybrid"])
db.append(["Nü Gui","Chinese","Vengeful female ghost"])
db.append(["Nukekubi","Japanese","Disembodied, flying head that attacks people"])
db.append(["Nuku-mai-tore","Māori","Forest spirit"])
db.append(["Nuli","Medieval Bestiary","Humanoid with backwards, eight-toed feet"])
db.append(["Numen","Roman","Tutelary spirit"])
db.append(["Nuno","Philippine","Malevolent little people"])
db.append(["Nuppeppo","Japanese","Animated chuck of dead flesh"])
db.append(["Nurarihyon","Japanese","Head-sized ball-like creature that floats in the sea and teases sailors"])
db.append(["Nure-onna","Japanese","Female monster who appears on the beach"])
db.append(["Nurikabe","Japanese","Spirit that manifests as an impassable, invisible wall"])
db.append(["Nyami Nyami","Tonga","Zimbabwean) mythology","The snake-spirit of the Zambezi River"])
db.append(["Nykštukas","Lithuanian","Cavern spirit"])
db.append(["Nymph","Greek","Nature spirit"])
db.append(["Obake","Japanese","Shapeshifting spirits"])
db.append(["Obariyon","Japanese","Spook which rides piggyback on a human victim and becomes unbearably heavy"])
db.append(["Obayifo","Ashanti","Vampiric possession spirit"])
db.append(["Obia","West Africa","Gigantic animal that serves witches"])
db.append(["Oceanid","Greek","Nymph daughters of Oceanus"])
db.append(["Odei","Basque","Storm spirit"])
db.append(["Odmience","Slavic","Changeling"])
db.append(["Og","Jewish","Giant king of the Amorites"])
db.append(["Ogre","Medieval folklore","Large, grotesque humanoid"])
db.append(["Ogun","Nigeria","god of Iron for the Yoruba people (South Western Nigeria)"])
db.append(["Oiwa","Japanese","Ghost of a woman with a distorted face who was murdered by her husband"])
db.append(["Ojáncanu","Cantabrian","Giant cyclops who embodies evil."])
db.append(["Okiku","Japanese","Spirit of a plate-counting servant girl, associated with the 'Okiku-Mushi' worm"])
db.append(["Ōkubi","Japanese","Death spirit"])
db.append(["Okuri-inu","Japanese","Dog or wolf that follows travelers at night. Similar to the Black dog of English folklore"])
db.append(["Ole-Higue","Guyanese","Vampiric hag who takes the form of a fireball at night"])
db.append(["Ōmukade","Japanese","Giant, human-eating centipede that lives in the mountains"])
db.append(["Onibi","Japanese","Spectral fire"])
db.append(["Oni","Japanese","Large, grotesque humanoid demon, usual having red skin and horns"])
db.append(["Onmoraki","Japanese","Bird-demon created from the spirits of freshly dead corpses"])
db.append(["Onocentaur","Medieval Bestiaries","Human-donkey hybrid"])
db.append(["Onoskelis","Greek","Shapeshifting demon"])
db.append(["Onryō","Japanese","Vengeful ghost that manifests in a physical rather than a spectral form"])
db.append(["Onza","Aztec and Latin American folklore","Wild cat, possibly a subspecies of cougar"])
db.append(["Oozlum bird","Unknown origin","Bird that flies backwards"])
db.append(["Ophiotaurus","Greek","Bull-serpent hybrid"])
db.append(["Opinicus","Heraldic","Lion-eagle hybrid, similar to a griffin, but with leonine forelimbs"])
db.append(["Orang Bunian","Malay","Forest spirit"])
db.append(["Orang Minyak","Malay","Spectral rapist"])
db.append(["Ördög","Hungarian","Shapeshifting demon"])
db.append(["Oread","Greek","Mountain nymph"])
db.append(["Ork","Tyrolean","Little people and house spirits"])
db.append(["Orobas","European","Horse-headed, honest oracle classed as a demon"])
db.append(["Orphan Bird","Medieval Bestiaries","Peacock-eagle-swan-crane hybrid"])
db.append(["Orthrus","Greek","Two-headed dog"])
db.append(["Oshun","Nigeria","god of love and fertility"])
db.append(["Otso","Finnish","Bear spirit"])
db.append(["Ouroboros","Worldwide","Mystic serpent/dragon that eats its own tail"])
db.append(["Ovinnik","Slavic","Malevolent threshing house spirit"])
db.append(["Paasselkä devils","Finnish","Spectral fire"])
db.append(["Pamola","Abenaki","Weather spirit"])
db.append(["Pandi","Medieval Bestiary","Humanoid with giant ears, eight fingers and toes, and white hair"])
db.append(["Panes","Greek","Human-goat hybrids descended from the god Pan"])
db.append(["Panis","Hindu","Demons with herds of stolen cows"])
db.append(["Panlong","Chinese","Water dragon"])
db.append(["Panotti","Medieval Bestiaries","Humanoid with gigantic ears"])
db.append(["Panther","Medieval Bestiaries","Feline with sweet breath"])
db.append(["Parandrus","Medieval Bestiaries","Shapeshifting animal whose natural form was a large ruminant"])
db.append(["Pardalokampoi","Etruscan","Fish-tailed panther"])
db.append(["Pard","Medieval Bestiaries","Fast, spotted feline believed to mate with lions to produce leopards"])
db.append(["Patagon","Medieval folklore","Giant race reputed to live in the area of Patagonia"])
db.append(["Patasola","Latin America","Anthropophagous, one-legged humanoid"])
db.append(["Patupairehe","Māori","White-skinned nature spirits"])
db.append(["Pech","Scottish","Strong little people"])
db.append(["Pegacorn","","Pegasus combined with a unicorn"])
db.append(["Pegaeae","Greek","Spring nymph"])
db.append(["Pegasus","Greek","Winged horse"])
db.append(["Pelesit","Malay","Servant spirit"])
db.append(["Peluda","French","Dragon"])
db.append(["Penanggalan","Philippine","Vampires that sever their heads from their bodies to fly around, usually with their intestines or other internal organs trailing behind"])
db.append(["Peng","Chinese","Giant bird"])
db.append(["Penghou","Chinese","Tree spirit"])
db.append(["Peri","Persian","Winged humanoid"])
db.append(["Peryton","Allegedly Medieval folklore","Deer-bird hybrid"])
db.append(["Pesanta","Catalan","Nightmare demon in the form of a cat or dog"])
db.append(["Peuchen","Chilota and Mapuche","Vampiric, flying, shapeshifting serpent"])
db.append(["Phi Tai Hong","Thai","the ghost of a person who has died suddenly of a violent or cruel death in Thai folklore"])
db.append(["Phoenix","Phoenician","Regenerative bird"])
db.append(["Piasa","Native American mythology","Winged, antlered feline-like dragon"])
db.append(["Piatek","Armenian","Large land animal"])
db.append(["Pictish Beast","Pictish stones","Stylistic animal, possibly a dragon"])
db.append(["Pillan","Mapuche","Nature spirit"])
db.append(["Pim-skwa-wagen-owad","Abenaki","Water spirit"])
db.append(["Piru","Finnish","Minor demon"])
db.append(["Pishacha","Hindu","Carrion-eating demon"])
db.append(["Pita-skog","Abenaki","Serpentine rain spirit"])
db.append(["Pixie","Cornish","Little people and nature spirits"])
db.append(["Pixiu","Chinese","Winged lion"])
db.append(["Pi yao","Chinese","Horned, dragon-lion hybrid"])
db.append(["Plakavac","Slavic","Vampire created when a mother strangles her child"])
db.append(["Pok-wejee-men","Abenaki","Tree spirit"])
db.append(["Polevik","Polish","Little people and field spirits"])
db.append(["Pollo Maligno","Colombian","Man-eating chicken spirit"])
db.append(["Polong","Malay","Invisible servant spirit"])
db.append(["Poltergeist","German","Ghost that moves objects"])
db.append(["Pombero","Guaraní","Wild man and nature spirit"])
db.append(["Ponaturi","Māori","Grotesque, malevolent humanoid"])
db.append(["Pontianak","Malay","Undead, vampiric women who died in childbirth"])
db.append(["Poukai","Māori","Giant bird"])
db.append(["Preta","Buddhist, Hindu, and Jain","Ghosts of especially greedy people"])
db.append(["Pricolici","Romanian","Roman","Undead wolf"])
db.append(["Psoglav","Serbia","Dog-headed monster"])
db.append(["Psotnik","Slavic","Mischievous spirit"])
db.append(["Psychai","Greek","Butterfly-winged nymphs, daughters of Psyche"])
db.append(["Pterippus","Greek","Winged horse"])
db.append(["Púca","Welsh","Shapeshifting animal spirit"])
db.append(["Puck","English","House spirit"])
db.append(["Puckwudgie","Native American mythology","Troll-like being with gray skin"])
db.append(["Pugot","Philippine","Headless humanoid"])
db.append(["Puk","Frisian","house spirit"])
db.append(["Púki","Icelandic","Malevolent little person"])
db.append(["Pūķis","Latvian","Malevolent house spirit"])
db.append(["Putz","German","House spirit"])
db.append(["Pygmy","Greek","Little people"])
db.append(["Pyrausta","Greek","Insect-dragon hybrid"])
db.append(["Python","Greek","Serpentine dragon"])
db.append(["Qalupalik","Inuit mythology)- Aquatic human abductor"])
db.append(["Qareen","Islamic","Personal demon"])
db.append(["Qilin","Chinese","Dragon-ox-deer hybrid"])
db.append(["Qiqirn","Inuit","Large, bald dog spirit"])
db.append(["Qliphoth","Jewish","Evil spirit"])
db.append(["Questing Beast","Arthurian legend","Serpent-leopard-lion-hart hybrid"])
db.append(["Quetzalcoatl","Aztec","An important god of the Aztec people; name meaning 'eathered serpent' Not to be confused with the quetzal, which is a type of bird"])
db.append(["Quinotaur","Frankish","Five-horned bull"])
db.append(["Rabisu","Akkadian","Vampiric spirit that ambushes people"])
db.append(["Radande","Swedish","Tree spirit"])
db.append(["Ragana","Lithuanian","Malevolent wizard"])
db.append(["Raijū","Japanese","Lightning spirit"])
db.append(["Rain Bird","Native American","Rain spirit"])
db.append(["Rainbow crow","Lenape","Crow spirit"])
db.append(["Rainbow Fish","Hindu","Whale-sized, multi-colored fish"])
db.append(["Rainbow Serpent","Australian Aboriginal","Snake"])
db.append(["Rakshasa","Buddhist and Hindu","Shapeshifting demon"])
db.append(["Ramidreju","Cantabrian","Extremely long, weasel-like animal"])
db.append(["Rå","Norse","Spirit that protects a specific place"])
db.append(["Raróg","Slavic","Whirlwind spirit"])
db.append(["Ratatoskr","Norse","Squirrel spirit"])
db.append(["Raven Mocker","Cherokee","Life-draining spirit"])
db.append(["Raven Spirit","Native American, Norse, and Siberian","Trickster spirit"])
db.append(["Redcap","English","Malevolent, grotesque humanoid"])
db.append(["Re’em","Jewish","Gigantic land animal"])
db.append(["Reichsadler","Heraldic","Eagle, sometimes depicted with two heads"])
db.append(["Rephaite","Jewish","Giant"])
db.append(["Reptilian humanoid","Global","Human-lizard hybrid"])
db.append(["Revenant","Medieval folklore","Reanimated dead"])
db.append(["Riva","English","wild-eyed creature of the future, sometimes bird"])
db.append(["Roc","Arabian and Persian","Gigantic bird"])
db.append(["Rokurokubi","Japanese","Long-necked, humanoid trickster"])
db.append(["Rompo","Africa and India","Skeletal creature with elements of a rabbit, badger, and bear"])
db.append(["Rồng","Vietnamese","Dragon"])
db.append(["Rougarou","French America","Human-wolf shapeshifter"])
db.append(["Rusalka","Slavic","Female water spirit"])
db.append(["Ryū","Japanese dragon"])
db.append(["Saci","Brazilian","One-legged nature-spirit"])
db.append(["Sagari","Japanese","Horse's head that dangles from trees on Kyūshū"])
db.append(["Sakabashira","Japanese","Haunted pillar, installed upside-down"])
db.append(["Salamander","Alchemy","Fire elemental"])
db.append(["Samebito","Japanese","Shark-man servant of the dragon king of the sea."])
db.append(["Samodiva","Slavic","Nature spirit"])
db.append(["Sampaati","Hindu","brother to the demi-god Jatayu"])
db.append(["Sandman","Northern Europe","Nursery spirit that induces sleep in children"])
db.append(["Sango","South Western Nigeria","King of Arts of Music, Dance and Entertainment in the Yoruba Culture"])
db.append(["Santelmo","Philippine","Spirits in a form of fireball, roaming around the forest"])
db.append(["Sânziană","Romanian","Nature spirit"])
db.append(["Sarimanok","Philippine","Bird of good fortune"])
db.append(["Sarngika","Hindu","Bird spirit"])
db.append(["Sarugami","Japanese","Wicked monkey spirit which was defeated by a dog"])
db.append(["Satori","Japanese","Mind-reading humanoid"])
db.append(["Satyr","Greek","Human-goat hybrid and fertility spirit"])
db.append(["Satyrus","Medieval Bestiary","Apes who always bear twins, one the mother loves, the other it hates"])
db.append(["Sazae-oni","Japanese","Shapeshifting turban snail spirit"])
db.append(["Sceadugenga","English","Shapeshifting undead"])
db.append(["Scitalis","Medieval Bestiaries","Snake which mesmerizes its prey"])
db.append(["Scorpion Man","Sumerian","Human-scorpion hybrid"])
db.append(["Scylla","Greek","Human-snake-wolf hybrid with a snake's tail, twelve wolf legs, and six long-necked wolf heads"])
db.append(["Sea-bee","Heraldic","Fish-tailed bee"])
db.append(["Sea monk","Medieval folklore","Fish-like humanoid"])
db.append(["Sea monster","Worldwide","Giant, marine animals"])
db.append(["Sea serpent","Worldwide","Serpentine sea monster"])
db.append(["Sea-Wyvern","Heraldic","Fish-tailed wyvern"])
db.append(["Seko","Japanese","Water spirit which can be heard making merry at night"])
db.append(["Selkie","Faroese, Icelandic, Irish, and Scottish","Human-seal shapeshifter"])
db.append(["Senpoku-Kanpoku","Japanese","Human-faced frog which guides the souls of the newly deceased to the graveyard"])
db.append(["Seps","Medieval Bestiaries","Snake with highly corrosive venom"])
db.append(["Serpent","Worldwide","Snake spirit"])
db.append(["Serpopard","Ancient Egypt","Serpent-leopard hybrid"])
db.append(["Shachihoko","Japanese","Tiger-carp hybrid"])
db.append(["Shade","Worldwide","Spiritual imprint"])
db.append(["Shadow People","American","Malevolent ghost"])
db.append(["Shahbaz","Persian","Giant eagle or hawk"])
db.append(["Shang-Yang","Chinese","Rain bird"])
db.append(["Shedim","Jewish","Chicken-legged demon"])
db.append(["Shedu","Akkadian and Sumerian","Protective spirit with the form of a winged bull or lion with a human head"])
db.append(["Shellycoat","English, Scottish and German, as schellenrocc","Water spirit"])
db.append(["Shen","Chinese","Shapeshifing sea monster"])
db.append(["Shenlong","Chinese","Weather dragon"])
db.append(["Shibaten","Japanese","Water spirit from Shikoku"])
db.append(["Shikigami","Japanese","Child-sized servant spirit"])
db.append(["Shiki-ōji","Japanese","Child-sized servant spirit"])
db.append(["Shikome","Japanese","Underworld hag"])
db.append(["Shinigami","Japanese","Death god"])
db.append(["Shiro-bōzu","Japanese","White, faceless spirit"])
db.append(["Shirouneri","Japanese","Animated mosquito netting or dust cloth"])
db.append(["Shiryō","Japanese","Spirit of a dead person"])
db.append(["Shisa","Japanese","Lion-dog hybrid"])
db.append(["Shishi","Chinese","Protective animal"])
db.append(["Shōjō","Japanese","Red-haired sea-sprites who love alcohol"])
db.append(["Shōkera","Japanese","Creature that peers in through skylights"])
db.append(["Shtriga","Albanian","An evil or dangerous witch"])
db.append(["Shug Monkey","English","Dog/monkey"])
db.append(["Shui Gui","Chinese","Drowned ghost"])
db.append(["Shunka Warakin","","(also shunka warak'in), an animal mentioned in American folklore that is said to resemble a wolf or hyena"])
db.append(["Shunoban","Japanese","Red-faced ghoul"])
db.append(["Shuten-dōji","Japanese","Ruler of the Oni"])
db.append(["Sídhe","Irish and Scottish","Ancestral or nature spirit"])
db.append(["Sigbin","Philippine","Goat-like vampire"])
db.append(["Sileni","Greek","Bald, fat, thick-lipped, and flat-nosed followers of Dionysus"])
db.append(["Simargl","Slavic","Winged dog"])
db.append(["Simurgh","Persian","Dog-lion-peacock hybrid"])
db.append(["Singa","Batak","Feline animal"])
db.append(["Sint Holo","Choctaw","Serpentine rain spirit"])
db.append(["Siren","Greek","Human-Fish Hybrid"])
db.append(["Sirin","Slavic","Demonic human-headed bird"])
db.append(["Sirrush","Akkadian","Dragon with aquiline hind legs and feline forelegs"])
db.append(["Sisiutl","Native American","Two-headed sea serpent"])
db.append(["Si-Te-Cah","Paiute","Red-haired giants"])
db.append(["Sjörå","Norse","Freshwater spirit"])
db.append(["Sjövættir","Norse","Sea spirit"])
db.append(["Skin-walker","Native American","Animal-human shapeshifter"])
db.append(["Skogsrå","Scandinavian","Forest spirit"])
db.append(["Skookum","Chinook Jargon","Hairy giant"])
db.append(["Skrzak","Slavic","Flying imp"])
db.append(["Sky Women","Polish","Weather spirit"])
db.append(["Sleipnir","Norse","eight-legged horse"])
db.append(["Sluagh","Irish and Scottish","Restless ghost"])
db.append(["Sodehiki-kozō","Japanese","Invisible spirit which pulls on sleeves"])
db.append(["Sōgenbi","Japanese","Fiery ghost of an oil-stealing monk"])
db.append(["Soragami","Japanese","Ritual disciplinary demon"])
db.append(["Soraki-gaeshi","Japanese","Sound of trees being cut down, when later none seem to have been cut"])
db.append(["Sorobanbōzu","Japanese","Ghost with an abacus"])
db.append(["Sōtangitsune","Japanese","Fox spirit from Kyoto"])
db.append(["Soucouyant","Trinidad and Tobago","Vampiric hag who takes the form of a fireball at night"])
db.append(["Spearfinger","Cherokee","Sharp-fingered hag"])
db.append(["Spectre","Worldwide","Terrifying ghost"])
db.append(["Sphinx","Greek","Winged lion with a woman's head"])
db.append(["Spiriduş","Romanian","Little people"])
db.append(["Spriggan","Cornish","Guardians of graveyards and ruins"])
db.append(["Sprite","Medieval folklore","little people, ghosts or elves"])
db.append(["Squonk","American","Ugly and lonely creature capable of evading capture by dissolving itself into a pool of tears"])
db.append(["Strigoi","Romanian","Vampire"])
db.append(["Strix","Roman","Vampiric bird"])
db.append(["Struthopodes","Medieval Bestiaries","Humanoid whose males have enormous feet, and females have tiny feet"])
db.append(["Strzyga","Slavic","Vampiric undead"])
db.append(["Stuhać","Slavic","Malevolent mountain spirit"])
db.append(["Stymphalian Bird","Greek","Metallic bird"])
db.append(["Suangi","New Guinea","Anthropophagous sorcerer"])
db.append(["Succubus","Medieval folklore","Female night-demon"])
db.append(["Sudice","Slavic","Fortune spirit"])
db.append(["Sunakake-baba","Japanese","Sand-throwing hag"])
db.append(["Sunekosuri","Japanese","Small dog- or cat-like creature that rubs against a person's legs at night"])
db.append(["Surma","Finnish","Hellhound"])
db.append(["Suzaku","Japanese","Japanese version of the Chinese Vermillion Bird"])
db.append(["Svaðilfari","Norse","unnatural strong horse, father of Sleipnir"])
db.append(["Svartálfar","Norse","Cavern spirits; the Black Elves"])
db.append(["Swan maiden","Worldwide","Swan-human shapeshifter"])
db.append(["Sylph","Alchemy","Air elemental"])
db.append(["Sylvan","Medieval folklore","Forest spirit"])
db.append(["Syrbotae","Medieval Bestiaries","African giant"])
db.append(["Syrictæ","Medieval Bestiaries","Reptilian humanoid"])
db.append(["Tachash","Jewish","Large land animal"])
db.append(["Taimatsumaru","Japanese","Tengu surrounded in demon fire"])
db.append(["Takam","Persian","Nature spirit"])
db.append(["Taka-onna","Japanese","Female spirit which can stretch itself to peer into the second story of a building"])
db.append(["Talos","Greek","Winged giant made of bronze"])
db.append(["Tangie","Scottish","Shapeshifting water spirit"])
db.append(["Taniwha","Māori","Water spirit"])
db.append(["Tantankororin","Japanese","Unharvested persimmon which becomes a monster"])
db.append(["Tanuki","Japanese","Shapeshifting Raccoon dog"])
db.append(["Taotao Mona","Mariana Islands","Ancestral spirits"])
db.append(["Taotie","Chinese","Greed spirit"])
db.append(["Tapairu","Mangaia","Nature spirit"])
db.append(["Tarasque","French","Dragon with leonine, turtle, bear, and human attributes"])
db.append(["Tartalo","Basque","One-eyed giant"])
db.append(["Tartaruchi","Christian","Demonic punisher"])
db.append(["Tatami-tataki","Japanese","Poltergeist that hits the tatami mats at night"])
db.append(["Tatsu","Japanese","dragon"])
db.append(["Taurokampoi","Etruscan","Fish-tailed bull"])
db.append(["Tavara","Trabzon","Night-demon"])
db.append(["Tecumbalam","Mayan","a bird"])
db.append(["Teju Jagua","Guaraní","Lizard with seven dog heads"])
db.append(["Tengu","Japanese","Anthropomorphic bird"])
db.append(["Tennin","Japanese","Angelic humanoid"])
db.append(["Te-no-me","Japanese","Ghost of a blind man, with his eyes on his hands"])
db.append(["Tepegoz","Azerbaijani","an Azerbaijani mythical creature similar to the cyclops Polyphemus"])
db.append(["Terrible Monster","Jewish","Lion-eagle-scorpion hybrid made from the blood of murder victims"])
db.append(["Teumessian Fox","Greek","Gigantic fox"])
db.append(["The Cu Bird","Mexican","El Pájaro Cu; a bird."])
db.append(["Theriocephalus","Medieval folklore","Animal-headed humanoid"])
db.append(["The Swallower","Ancient Egyptian","Crocodile-leopard-hippopotamus hybrid"])
db.append(["Three-legged bird","Asia and Africa","Solar bird"])
db.append(["Thunderbird","Native American","Avian lightning spirit, bird"])
db.append(["Tiangou","Chinese","Meteoric dog"])
db.append(["Tianlong","Chinese","Celestial dragon"])
db.append(["Tibicena","Canarian","Evil Dog"])
db.append(["Tiddy Mun","English","Bog spirit"])
db.append(["Tigmamanukan","Philippine","an Asian fairy bluebird believed in as part of Philippine mythology"])
db.append(["Tigris","Jewish","Giant lion"])
db.append(["Tikbalang","Philippine","Anthropomorphic horse"])
db.append(["Tikoloshe","Zulu","Little people and water spirit"])
db.append(["Timingila","Hindu","Sea monster"])
db.append(["Tipua","Māori","Spirit that protects a specific place"])
db.append(["Titan","Greek","Giant"])
db.append(["Tiyanak","Philippine","Malevolent spirit in the form of a human infant"])
db.append(["Tizheruk","Inuit","Sea serpent"])
db.append(["Tlahuelpuchi","Tlaxcalan","Shapeshifting vampire"])
db.append(["Tōfu-kozō","Japanese","Spirit child carrying a block of tofu"])
db.append(["Toire-no-Hanakosan","Japanese","Ghost who lurks in grade school restroom stalls"])
db.append(["Tomte","Scandinavian","House spirit"])
db.append(["Topielec","Slavic","Water spirit"])
db.append(["Tōtetsu","Japanese","Greed spirit"])
db.append(["Toyol","Malay","Servant spirit"])
db.append(["Trasgo","Spanish and Portuguese","Grotesque, mischievous little people"])
db.append(["Trauco","Chilota","Fertility spirit"])
db.append(["Trenti","Cantabrian","Diminutive demon"])
db.append(["Tripurasura","Hindu","Demonic inhabitants of Tripura"])
db.append(["Tritons","Greek","Human-fish hybrid"])
db.append(["Troll","Norse","Nature spirit"])
db.append(["Trow","Orkney and Shetland","Little people and nature spirits"])
db.append(["Tsi-noo","Abenaki","Vampiric demon"])
db.append(["Tsuchigumo","Japanese","Shapeshifting, giant spider"])
db.append(["Tsuchinoko","Japanese","Plump snake-like creature"])
db.append(["Tsukumogami","Japanese","Inanimate object that becomes animated after existing for 100 years"])
db.append(["Tsul 'Kalu","Cherokee","Giant nature spirit"])
db.append(["Tsurara-onna","Japanese","Icicle woman"])
db.append(["Tsurube-otoshi","Japanese","Monster which drops or lowers a bucket from the top of a tree to catch people"])
db.append(["Tugarin Zmeyevich","Slavic","Evil shapeshifter"])
db.append(["Tupilaq","Inuit","Animated construct"])
db.append(["Turehu","Māori","Pale spirit"])
db.append(["Turul","Hungarian","a giant falcon that helped shape the origins of the Magyars"])
db.append(["Tylwyth Teg","Welsh","Nature spirit"])
db.append(["Typhon","Greek","Winged, snake-legged giant"])
db.append(["Tzitzimitl","Aztec","Skeletal star spirit"])
db.append(["Ubume","Japanese","Ghosts of women who died in childbirth"])
db.append(["Uma-no-ashi","Japanese","Horse's leg which dangles from a tree and kicks passersby"])
db.append(["Umibōzu","Japanese","Ghost of drowned priest"])
db.append(["Umi-nyōbō","Japanese","Female sea monster who steals fish"])
db.append(["Undead","Worldwide","Dead that behave as if alive"])
db.append(["Underwater panther","Native American","Feline water spirit"])
db.append(["Undine","Alchemy","Water elemental"])
db.append(["Unhcegila","Lakota","Dragon"])
db.append(["Unicorn","Medieval Bestiaries","Horse with magical healing horn."])
db.append(["Unktehi","Lakota","Serpentine rain spirit"])
db.append(["Unktehila","Lakota","Reptilian water monster"])
db.append(["Upinis","Lithuanian","River spirit"])
db.append(["Urayuli","Native American","Hairy giant"])
db.append(["Uriaş","Romanian","Giant"])
db.append(["Urmahlullu","Mesopotamian","Lion-human hybrid guardian spirit"])
db.append(["Ushi-oni","Japanese","Bull-headed monster"])
db.append(["Utukku","Akkadian","Underworld messenger spirit"])
db.append(["Uwan","Japanese","Spirit that shouts to surprise people"])
db.append(["Vadātājs","Latvian","Spirit that misleads people"])
db.append(["Vættir","Norse","Nature spirit"])
db.append(["Valkyrie","Norse","Female spirit that leads souls of dead warriors to Valhalla"])
db.append(["Valravn","Danish","Supernatural raven"])
db.append(["Vâlvă","Romanian","Female nature spirit"])
db.append(["Vampire","Slavic","Reanimated corpse that subsists on blood"])
db.append(["Vanara","Hindu","Human-ape hybrid"])
db.append(["Vântoase","Romanian","Female weather spirit"])
db.append(["Varaha","Hindu mythology","third Avatar of Vishnu in the form of a boar"])
db.append(["Vârcolac","Romanian","Vampire or werewolf"])
db.append(["Vardøger","Scandinavian","Ghostly double"])
db.append(["Vedrfolnir","Norse","a hawk sitting between the eyes of an eagle in the crown of Yggdrasill, the World Tree"])
db.append(["Veļi","Latvian","Ghost, shade, formed after a death of a human"])
db.append(["Věri Şělen","Chuvash","dragon"])
db.append(["Vetala","Hindu","Corpses possessed by vampiric spirits"])
db.append(["Víbria","Catalan","Dragon with breasts and an eagle's beak"])
db.append(["Víðópnir,","Norse","Rooster that sits atop the tree"])
db.append(["Vielfras","German","Gluttonous dog-cat-fox hybrid"])
db.append(["Vila","Slavic","Weather spirit"])
db.append(["Vilkacis","Latvian","Animalistic, werewolf-like monster"])
db.append(["Viruñas","Colombian","Handsome demon"])
db.append(["Vision Serpent","Mayan","Mystical dragon"])
db.append(["Vodyanoy","Slavic","Male water spirit"])
db.append(["Vrykolakas","Greek","Undead wolf-human hybrid"])
db.append(["Waldgeist","German","Forest spirit"])
db.append(["Wana-games-ak","Abenaki","Water spirits"])
db.append(["Wani","Japanese","A crocodilian water monster"])
db.append(["Wanyūdō","Japanese","Demon in the form of a burning ox cart with a human head"])
db.append(["Warak ngendog","Indonesian Muslim","Egg-laying bird"])
db.append(["Warg","English and Scandinavian O.N. vargr","Giant, demonic wolf"])
db.append(["Wassan-mon-ganeehla-ak","Abenaki","Aurora spirits"])
db.append(["Water monkey","Chinese","Water spirit"])
db.append(["Water sprite","Alchemy","Water elemental"])
db.append(["Wati-kutjara","Australia Aboriginal","Goanna spirits"])
db.append(["Wa-won-dee-a-megw","Abenaki","Shapeshifting snail spirit"])
db.append(["Weisse Frauen","German","Female spirit"])
db.append(["Wekufe","Mapuche","Demon"])
db.append(["Wendigo","Algonquian","Anthropophagous spirit"])
db.append(["Wentshukumishiteu","Inuit","Water spirit"])
db.append(["Werecat","Worldwide","Feline-human shapeshifter"])
db.append(["Werehyena","Africa","Hyena-human shapeshifter"])
db.append(["Werewolf","Worldwide","Wolf-human shapeshifter"])
db.append(["White Lady","Worldwide","Ghost of a murdered or mistreated woman"])
db.append(["Wild man","European","Hairy, bipedal man-like creature"])
db.append(["Will-o'-the-Wisp","Worldwide","Spectral fire"])
db.append(["Wirry-cow","Scottish","Malevolent spirit"])
db.append(["Witte Wieven","Dutch","Female, ancestral spirit"])
db.append(["Wolpertinger","German","a forest animal comprised from various animal parts (similar to a Chimera)"])
db.append(["Wondjina","Australia Aboriginal","Weather spirit"])
db.append(["Wraith","Scottish","Water spirit or ghostly apparition"])
db.append(["Wulver","Scottish","Wolf-headed human"])
db.append(["Wu Tou Gui","Chinese","Beheaded ghost"])
db.append(["Wyrm","English","dragon"])
db.append(["Wyvern","Germanic Heraldic","Flying reptile, usually with two legs and two wings"])
db.append(["Xana","Asturian","Female water spirit"])
db.append(["Xecotcovach","Mayan","a bird"])
db.append(["Xelhua","Aztec","Giant"])
db.append(["Xindhi","Albanian","Elves"])
db.append(["Xing Tian","Chinese","Headless giant"])
db.append(["Xiuhcoatl","Aztec","Drought spirit"])
db.append(["Yacumama","South America","Sea monster"])
db.append(["Yacuruna","Indigenous people of the Amazon","Mythical water people, with backwards heads and feet"])
db.append(["Yadōkai","Japanese","Malevolent, nocturnal spirit"])
db.append(["Yagyō-san","Japanese","Demon who rides through the night on a headless horse"])
db.append(["Yaksha","Buddhist, Hindu, and Jainism","Male nature spirit"])
db.append(["Yakshi","Keralite","Vampire"])
db.append(["Yakshini","Buddhist, Hindu, and Jainism","Female nature spirit"])
db.append(["Yakubyō-gami","Japanese","Disease and misfortune spirit"])
db.append(["Yale","Medieval Bestiaries","Antelope- or goat-like animal with swiveling horns"])
db.append(["Yali","Hindu","Lion-like beast"])
db.append(["Yallery-Brown","English","Nature spirit"])
db.append(["Yama-biko","Japanese","Echo spirit"])
db.append(["Yama-bito","Japanese","Savage, mountain-dwelling humanoid"])
db.append(["Yama-chichi","Japanese","Monkey-like mountain spirit"])
db.append(["Yama-inu","Japanese","Dog-like mountain spirit"])
db.append(["Yama-otoko","Japanese","Mountain giant"])
db.append(["Yamata no Orochi","Japanese","Gigantic, eight-headed serpent"])
db.append(["Yama-uba","Japanese","Malevolent, mountain-dwelling hag"])
db.append(["Yama-waro","Japanese","Hairy, one-eyed spirit"])
db.append(["Yanari","Japanese","Spirit which causes strange noises"])
db.append(["Yaoguai","Japanese","Animalistic demon"])
db.append(["Yara-ma-yha-who","Australian Aboriginal","Diminutive, sucker-fingered vampire"])
db.append(["Yatagarasu","Japanese","Three-legged crow of Amaterasu"])
db.append(["Yato-no-kami","Japanese","Serpent spirits"])
db.append(["Yeth hound","English","Headless dog"])
db.append(["Yeti","Himalayan","Mountain Bigfoot"])
db.append(["Yilbegän","Turkic","Either a dragon or a giant"])
db.append(["Yobuko","Japanese","Mountain dwelling spirit"])
db.append(["Yōkai","Japanese","Supernatural Monster"])
db.append(["Yomotsu-shikome","Japanese","Underworld hag"])
db.append(["Yong","Korean","dragon"])
db.append(["Yōsei","Japanese","Fairy"])
db.append(["Yosuzume","Japanese","Mysterious bird that sings at night, sometimes indicating that the okuri-inu is near"])
db.append(["You Hun Ye Gui","Chinese","Wandering ghost"])
db.append(["Yowie","Australian Aboriginal","Nocturnal human-ape hybrid, also Yahoo"])
db.append(["Ypotryll","Heraldic","Boar-camel-ox-serpent hybrid"])
db.append(["Yuan Gui","Chinese","Distressed ghost"])
db.append(["Yukinko","Japanese","Childlike snow spirit"])
db.append(["Yuki-onna","Japanese","Snow spirit"])
db.append(["Yūrei","Japanese","Ghost"])
db.append(["Yuxa","Tatar","100-year-old snake that transforms into a beautiful human"])
db.append(["Zahhak","Persian","Dragon"])
db.append(["Žaltys","Baltic","Serpentine fertility spirit"])
db.append(["Zamzummim","Jewish","Giant"])
db.append(["Zână","Romanian","Nature spirit"])
db.append(["Zashiki-warashi","Japanese","House spirit"])
db.append(["Zburator","Romanian","Wolf-headed dragon"])
db.append(["Zduhać","Slavic mythology","Disembodied, heroic spirit"])
db.append(["Zennyo Ryūō","Japanese","Rain-making dragon"])
db.append(["Zeus","Greece","God of the sky, lightning, thunder, law, order, justice"])
db.append(["Zhar-Ptitsa","Slavic","Glowing bird"])
db.append(["Zhulong","Chinese","Pig-headed dragon"])
db.append(["Zhū Què","Chinese","Fire elemental bird"])
db.append(["Žiburinis","Lithuanian","Forest spirit in the form of a glowing skeleton"])
db.append(["Zilant","Tatar","Flying reptile with chicken legs"])
db.append(["Zin","West Africa","Water spirits"])
db.append(["Ziz","Jewish","Giant Bird"])
db.append(["Zlatorog","Slovenia","White deer with golden horns"])
db.append(["Zmeu","Romanian folklore","Giant with a habit of kidnapping young girls"])
db.append(["Zmiy","Slavic dragon"])
db.append(["Zombie","Vodou/Worldwide","Re-animated corpse"])
db.append(["Zorigami","Japanese","Animated clock"])
db.append(["Zuijin","Japanese","Tutelary spirit"])
db.append(["Zunbera-bō","Japanese","Faceless ghost"])
db.append(["Meiga","Galicia","Witch"])
db.append(["Galchagorry","País Vasco","pronunciation: Galchagorry"])


def adjetivo():
  n = random.randint(0, len(adj)-1)
  return adj[n]

def bestia():
  n = random.randint(0, len(db)-1)
  return db[n]

if __name__ == '__main__':
  a=adjetivo()
  b=bestia()
  
  print "\ngenerador.py\nversion: %s - %s" % (VERSION, VERSION_NAME)
  
  print "\n => %s %s" % (a, b[0])
  print "  ::%s\n   ::%s" % (b[1], b[2])